#!/usr/bin/env python3
"""
build-catalog.py — writes catalog/catalog.json, and is the reason it can be
trusted.

The catalogue is DATA: every item is a name, a picture and a list of actions
out of the vocabulary genesi-store implements. Nothing in it is code. But the
picture comes from somewhere, and "somewhere" is the part that rots -- links
die, files are replaced, repositories are renamed. So the catalogue is not
hand-written: it is generated by this script, which

  * fetches every wallpaper it lists and records the SIZE and the SHA-256 it
    got, so the store can refuse a file that changed under it;
  * reads caelestia's own scheme files to get the colours each theme card is
    painted in, rather than a person retyping thirty palettes;
  * fails loudly on a link that does not answer, so a dead item is a build
    failure here instead of a broken card on somebody's desktop.

Re-run it when adding items, or to refresh what the links serve:

    python3 build-catalog.py            # verify and write
    python3 build-catalog.py --offline  # rebuild the text-only items

Sources, and why these: the wallpapers come from one MIT-licensed collection
(D3Ext/aesthetic-wallpapers), so there is a single licence to honour and a
single repository to check rather than twenty. The colour schemes come from
caelestia-cli, which is already installed -- applying one downloads nothing at
all. The bar arrangements are Genesi's own presets, already shipped.
"""
import hashlib
import io
import json
import os
import sys
import time
import urllib.request

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "catalog", "catalog.json")
OFFLINE = "--offline" in sys.argv

WALL_REPO = "https://raw.githubusercontent.com/D3Ext/aesthetic-wallpapers/main/images/"
SCHEME_REPO = ("https://raw.githubusercontent.com/caelestia-dots/cli/main/"
               "src/caelestia/data/schemes/")

SECTIONS = [
    {"id": "discover", "label": "Descobrir", "label_en": "Discover",
     "icon": "home", "blurb": "O que vale a pena hoje."},
    {"id": "rices", "label": "Ambientes", "label_en": "Rices", "icon": "grid",
     "blurb": "Um desktop inteiro, de uma vez."},
    {"id": "themes", "label": "Temas", "label_en": "Themes", "icon": "palette",
     "blurb": "A cor de tudo, do topo ao terminal."},
    {"id": "lockscreens", "label": "Telas de bloqueio", "label_en": "Lockscreens",
     "icon": "lock", "blurb": "A da sessão e a do login, que são duas."},
    {"id": "bars", "label": "Barras", "label_en": "Bar styles", "icon": "bar",
     "blurb": "Quinze arranjos da barra."},
    {"id": "fastfetch", "label": "Fastfetch", "label_en": "Fastfetch",
     "icon": "terminal", "blurb": "O cartão de visita do terminal."},
    {"id": "decor", "label": "Decoração", "label_en": "Decor", "icon": "image",
     "blurb": "Papéis de parede e detalhes."},
    {"id": "bundles", "label": "Coleções", "label_en": "Bundles", "icon": "box",
     "blurb": "Combinações que já vêm casadas."},
    {"id": "plugins", "label": "Plugins", "label_en": "Plugins", "icon": "plug",
     "blurb": "Em breve."},
]

# ── Wallpapers ──────────────────────────────────────────────────────────────
# Chosen to lead with Genesi's own weather -- forest, water, green light --
# and then widen. The name is what a person reads; the file is what the link
# serves.
WALLS = [
    ("forest-dark", "dark_forest.png", "Floresta Escura",
     "Mata fechada ao anoitecer.", ["natureza", "escuro", "verde"]),
    ("nature", "nature.jpg", "Natureza",
     "Verde aberto, sem pressa.", ["natureza", "verde"]),
    ("everforest-robin", "everforest_robin.png", "Everforest",
     "A paleta everforest em desenho.", ["natureza", "verde", "arte"]),
    ("lake", "lake.jpg", "Lago",
     "Água parada e montanha.", ["natureza", "agua", "calmo"]),
    ("art-lake", "art-lake.png", "Lago Ilustrado",
     "O mesmo silêncio, desenhado.", ["arte", "agua", "calmo"]),
    ("mountains", "mountains.png", "Montanhas",
     "Camadas até o horizonte.", ["natureza", "minimalista"]),
    ("golden-mountains", "golden-mountains.png", "Montanhas Douradas",
     "Fim de tarde nos picos.", ["natureza", "quente"]),
    ("oled-mountains", "oled-mountains.jpg", "Montanhas OLED",
     "Preto real, para telas OLED.", ["escuro", "oled", "minimalista"]),
    ("moon", "moon.png", "Lua",
     "Uma lua e nada mais.", ["escuro", "minimalista", "noite"]),
    ("falltree", "falltree.jpg", "Outono",
     "Uma árvore em queda de folhas.", ["natureza", "quente"]),
    ("green-sun", "green-sun.jpg", "Sol Verde",
     "Luz filtrada por folhas.", ["verde", "natureza"]),
    ("tree-castle", "tree-nature-castleinsky.png", "Castelo no Céu",
     "Árvore, castelo, nuvem.", ["arte", "natureza"]),
    ("ink-wave", "ink_wave.png", "Onda de Tinta",
     "Nanquim em movimento.", ["arte", "escuro", "minimalista"]),
    ("blue-waves", "blue-waves.png", "Ondas Azuis",
     "Curvas frias e limpas.", ["minimalista", "frio"]),
    ("minimal-c", "minimal_c.png", "Minimal",
     "Quase nada, bem colocado.", ["minimalista", "escuro"]),
    ("arch-nord", "arch-nord-dark.png", "Arch Nord",
     "O logo, em nord.", ["escuro", "frio", "arch"]),
    ("gruvbox-city", "gruvbox_retrocity.png", "Cidade Gruvbox",
     "Retro em terra e mostarda.", ["quente", "retro", "cidade"]),
    ("neocity", "neocity.png", "Neocidade",
     "Neon e chuva.", ["cidade", "escuro", "neon"]),
]

# ── Colour schemes ─────────────────────────────────────────────────────────
# (family, flavour, mode, name, blurb). Everything here ships with
# caelestia-cli, so applying one is instant and offline.
SCHEMES = [
    ("caelestia", "default", "dark", "Caelestia", "O tom da casa, no escuro."),
    ("caelestia", "default", "light", "Caelestia Claro", "O mesmo, na luz."),
    ("darkgreen", "hard", "dark", "Verde Profundo", "Quase preto, com seiva."),
    ("darkgreen", "medium", "dark", "Verde Mata", "Verde sem gritar."),
    ("everforest", "medium", "dark", "Everforest", "Musgo, pedra e madeira."),
    ("everforest", "hard", "dark", "Everforest Duro", "O mesmo, com mais contraste."),
    ("everforest", "medium", "light", "Everforest Claro", "Papel e folha."),
    ("everblush", "medium", "dark", "Everblush", "Escuro com um rubor."),
    ("catppuccin", "mocha", "dark", "Catppuccin Mocha", "O pastel que todo mundo conhece."),
    ("catppuccin", "macchiato", "dark", "Catppuccin Macchiato", "Um passo mais claro."),
    ("catppuccin", "frappe", "dark", "Catppuccin Frappe", "Meio do caminho."),
    ("catppuccin", "latte", "light", "Catppuccin Latte", "Claro, sem estourar."),
    ("gruvbox", "medium", "dark", "Gruvbox", "Terra, mostarda e ferrugem."),
    ("gruvbox", "hard", "dark", "Gruvbox Duro", "Fundo mais fechado."),
    ("gruvbox", "soft", "dark", "Gruvbox Macio", "Fundo mais aberto."),
    ("gruvbox", "medium", "light", "Gruvbox Claro", "O mesmo, de dia."),
    ("nord", "medium", "dark", "Nord", "Gelo e aço."),
    ("tokyonight", "medium", "dark", "Tokyo Night", "Cidade às três da manhã."),
    ("rosepine", "main", "dark", "Rose Pine", "Vinho e pinho."),
    ("rosepine", "moon", "dark", "Rose Pine Moon", "Um pouco mais alto."),
    ("rosepine", "dawn", "light", "Rose Pine Dawn", "O amanhecer da mesma."),
    ("dracula", "medium", "dark", "Dracula", "Roxo clássico."),
    ("onedark", "default", "dark", "One Dark", "O tema de editor virou desktop."),
    ("oldworld", "default", "dark", "Old World", "Sepia e quieto."),
    ("solarized", "medium", "dark", "Solarized", "O mais estudado de todos."),
    ("shadotheme", "default", "dark", "Shado", "Cinza com um fio de cor."),
]

# ── Bar arrangements ───────────────────────────────────────────────────────
# Genesi's own presets, already installed by genesi-caelestia-settings.
BARS = [
    ("10-padrao", "Padrão", "A barra como o caelestia entrega."),
    ("15-borda", "Rente", "Sem moldura: encostada na borda da tela."),
    ("20-centrado", "Centralizado", "Logo em cima, espaços no meio, o resto embaixo."),
    ("25-fio", "Fio", "O mais estreito que dá para acertar com o mouse."),
    ("30-ilha", "Ilha", "Cantos bem redondos, barra na beirada."),
    ("40-numeros", "Numeros", "Espaços de trabalho numerados."),
    ("45-arejado", "Arejado", "Mais espaço entre tudo."),
    ("50-janelas", "Janelas", "Mostra as janelas abertas."),
    ("55-painel", "Painel", "Denso, como um painel de controle."),
    ("60-informativo", "Informativo", "Tudo que dá para medir, medido."),
    ("70-compacto", "Compacto", "O essencial, junto."),
    ("80-limpo", "Limpo", "So o necessario."),
    ("85-relogio", "Relogio", "O relógio em primeiro lugar."),
    ("90-trilha", "Trilha", "Uma linha contínua."),
    ("95-oculta", "Oculta", "Some até você precisar."),
]


def get(url, binary=False):
    request = urllib.request.Request(url, headers={"User-Agent": "genesi-store-build"})
    with urllib.request.urlopen(request, timeout=45) as response:
        data = response.read()
    return data if binary else data.decode("utf-8")


def scheme_colours(family, flavour, mode):
    """The five colours a theme card is painted in, from caelestia's own file."""
    url = "%s%s/%s/%s.txt" % (SCHEME_REPO, family, flavour, mode)
    want = ("background", "onBackground", "primary", "secondary", "tertiary")
    found = {}
    for line in get(url).splitlines():
        parts = line.split()
        if len(parts) == 2 and parts[0] in want:
            found[parts[0]] = "#" + parts[1].lower()
    missing = [k for k in want if k not in found]
    if missing:
        raise SystemExit("scheme %s/%s/%s has no %s"
                         % (family, flavour, mode, ", ".join(missing)))
    return found


def wallpaper_asset(filename):
    url = WALL_REPO + filename
    data = get(url, binary=True)
    kind = "image/png" if filename.endswith(".png") else "image/jpeg"
    head = {"image/png": b"\x89PNG", "image/jpeg": b"\xff\xd8\xff"}[kind]
    if not data.startswith(head):
        raise SystemExit("%s is not %s -- the link is broken" % (url, kind))
    return {"url": url, "type": kind, "bytes": len(data),
            "sha256": hashlib.sha256(data).hexdigest()}


def build():
    previous = {}
    if os.path.exists(OUT):
        with io.open(OUT, encoding="utf-8") as fh:
            for item in json.load(fh).get("items", []):
                previous[item["id"]] = item

    items = []

    # ── Themes ─────────────────────────────────────────────────────────────
    for family, flavour, mode, name, blurb in SCHEMES:
        ident = "theme-%s-%s-%s" % (family, flavour, mode)
        # Offline reuses the COLOURS, which came off the network, and rebuilds
        # the item around them. Reusing the whole item meant a change to a name
        # or a tag silently did not happen on an offline build.
        if OFFLINE and ident in previous:
            colours = {"background": previous[ident]["preview"]["background"],
                       "onBackground": previous[ident]["preview"]["ink"],
                       "primary": previous[ident]["preview"]["colours"][0],
                       "secondary": previous[ident]["preview"]["colours"][1],
                       "tertiary": previous[ident]["preview"]["colours"][2]}
        else:
            colours = scheme_colours(family, flavour, mode)
        items.append({
            "id": ident,
            "section": "themes",
            "name": name,
            "blurb": blurb,
            "author": "caelestia / %s" % family,
            "mode": mode,
            "tags": ["escuro" if mode == "dark" else "claro", family],
            "preview": {"kind": "swatches",
                        "background": colours["background"],
                        "ink": colours["onBackground"],
                        "colours": [colours["primary"], colours["secondary"],
                                    colours["tertiary"]]},
            "actions": [{"action": "scheme", "name": family,
                         "flavour": flavour, "mode": mode}],
        })

    # ── Decor: wallpapers ──────────────────────────────────────────────────
    for ident, filename, name, blurb, tags in WALLS:
        full = "wall-" + ident
        if OFFLINE and full in previous:
            asset = previous[full]["assets"]["picture"]
        else:
            asset = wallpaper_asset(filename)
        items.append({
            "id": full,
            "section": "decor",
            "name": name,
            "blurb": blurb,
            "author": "D3Ext/aesthetic-wallpapers",
            "license": "MIT",
            "source": "https://github.com/D3Ext/aesthetic-wallpapers",
            "tags": tags,
            "preview": {"kind": "image", "asset": "picture"},
            "assets": {"picture": asset},
            "actions": [{"action": "wallpaper", "asset": "picture"}],
        })

    # ── Bar styles ─────────────────────────────────────────────────────────
    for preset, name, blurb in BARS:
        items.append({
            "id": "bar-" + preset.split("-", 1)[1],
            "section": "bars",
            "name": name,
            "blurb": blurb,
            "author": "Genesi",
            "tags": ["barra"],
            "preview": {"kind": "bar", "preset": preset},
            "actions": [{"action": "bar", "preset": preset}],
        })

    for extra in (lockscreens(), fastfetch(), rices(previous), bundles()):
        items.extend(extra)

    data = {
        "version": 1,
        "updated": time.strftime("%Y-%m-%d"),
        "sections": SECTIONS,
        "items": items,
    }
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with io.open(OUT, "w", encoding="utf-8", newline="\n") as fh:
        json.dump(data, fh, indent=1, ensure_ascii=False, sort_keys=False)
        fh.write("\n")
    print("catalog: %d items across %d sections" % (len(items), len(SECTIONS)))
    for section in SECTIONS:
        count = len([i for i in items if i["section"] == section["id"]])
        print("  %-12s %d" % (section["id"], count))


# ── The text-only shelves ──────────────────────────────────────────────────


HYPRLOCK_BASE = """# %s -- written by Genesi Store.
# hyprlock's own format; edit freely, the store keeps a copy of what was here.

general {
    hide_cursor = true
    grace = 0
    no_fade_in = false
}

background {
    monitor =
    path = %s
    blur_passes = %d
    blur_size = %d
    brightness = %s
    contrast = 1.0
    vibrancy = 0.17
}

input-field {
    monitor =
    size = 320, 52
    outline_thickness = 2
    dots_size = 0.24
    dots_spacing = 0.3
    dots_center = true
    outer_color = %s
    inner_color = %s
    font_color = %s
    fade_on_empty = false
    placeholder_text = <i>%s</i>
    hide_input = false
    rounding = %d
    position = 0, -90
    halign = center
    valign = center
}

label {
    monitor =
    text = $TIME
    font_size = %d
    font_family = %s
    color = %s
    position = 0, 160
    halign = center
    valign = center
}

label {
    monitor =
    text = %s
    font_size = 16
    font_family = %s
    color = %s
    position = 0, 96
    halign = center
    valign = center
}
"""


def lock_item(ident, name, blurb, tags, text, preview):
    """A session lock: the config file, and the locker it needs to exist."""
    return {
        "id": "lock-" + ident,
        "section": "lockscreens",
        "name": name,
        "blurb": blurb,
        "family": "session",
        "author": "Genesi",
        "tags": ["sessão"] + tags,
        "preview": preview,
        "actions": [
            {"action": "package", "name": "hyprlock", "binary": "hyprlock"},
            {"action": "file", "path": "~/.config/hypr/hyprlock.conf",
             "text": text},
        ],
    }


def lockscreens():
    out = []
    out.append(lock_item(
        "wallpaper", "Papel de parede", "O seu papel de parede, desfocado.",
        ["desfoque"],
        HYPRLOCK_BASE % ("Papel de parede", "screenshot", 3, 8, "0.7",
                         "rgba(143, 214, 171, 0.9)", "rgba(20, 28, 24, 0.75)",
                         "rgba(233, 245, 238, 1.0)", "senha", 14, 96,
                         "Rubik", "rgba(233, 245, 238, 0.95)",
                         "$USER", "Rubik", "rgba(143, 214, 171, 0.85)"),
        {"kind": "lock", "background": "#14241c", "accent": "#8fd6ab"}))
    out.append(lock_item(
        "clean", "Limpa", "Fundo sólido, relógio grande, nada mais.",
        ["minimalista"],
        HYPRLOCK_BASE % ("Limpa", "", 0, 0, "1.0",
                         "rgba(143, 214, 171, 0.8)", "rgba(16, 20, 18, 0.9)",
                         "rgba(240, 244, 241, 1.0)", "digite a senha", 8, 120,
                         "Rubik", "rgba(240, 244, 241, 0.95)",
                         "", "Rubik", "rgba(143, 214, 171, 0.8)"),
        {"kind": "lock", "background": "#101412", "accent": "#8fd6ab"}))
    out.append(lock_item(
        "night", "Noite", "Escuro de verdade, para não acordar ninguém.",
        ["escuro", "oled"],
        HYPRLOCK_BASE % ("Noite", "screenshot", 4, 10, "0.35",
                         "rgba(120, 160, 140, 0.7)", "rgba(0, 0, 0, 0.85)",
                         "rgba(200, 220, 208, 1.0)", "senha", 20, 84,
                         "Rubik", "rgba(200, 220, 208, 0.9)",
                         "$TIME", "Rubik", "rgba(120, 160, 140, 0.7)"),
        {"kind": "lock", "background": "#000000", "accent": "#78a08c"}))
    out.append(lock_item(
        "terminal", "Terminal", "Monoespaçada, como um prompt.",
        ["mono", "retro"],
        HYPRLOCK_BASE % ("Terminal", "screenshot", 1, 4, "0.5",
                         "rgba(143, 214, 171, 1.0)", "rgba(10, 14, 12, 0.9)",
                         "rgba(143, 214, 171, 1.0)", "login:", 2, 72,
                         "CaskaydiaCove Nerd Font", "rgba(143, 214, 171, 1.0)",
                         "$USER@$(hostname)", "CaskaydiaCove Nerd Font",
                         "rgba(143, 214, 171, 0.7)"),
        {"kind": "lock", "background": "#0a0e0c", "accent": "#8fd6ab"}))

    # ── The other lock: the screen BEFORE the session ──────────────────────
    #
    # Different machinery entirely -- SDDM, running as root, before anyone has
    # logged in -- so these are their own family, and the app says so. Only
    # themes that are already installed are offered: a login screen pointed at
    # a theme that is not there is a login screen that does not come up, and
    # that is not a thing to find out by rebooting.
    for ident, theme, name, blurb in (
            ("breeze", "breeze", "Breeze (padrão)",
             "A tela que o sistema instala."),
            ("elarun", "elarun", "Elarun",
             "Enviada com o SDDM: sóbria, centralizada."),
            ("maldives", "maldives", "Maldives",
             "Enviada com o SDDM: foto de fundo, campo ao centro."),
            ("maya", "maya", "Maya",
             "Enviada com o SDDM: escura e discreta.")):
        out.append({
            "id": "login-" + ident,
            "section": "lockscreens",
            "name": name,
            "blurb": blurb,
            "family": "login",
            "author": "SDDM",
            "tags": ["login", "antes da sessão"],
            "needs_root": True,
            "preview": {"kind": "login", "theme": theme},
            "actions": [{"action": "login", "theme": theme}],
        })
    return out


FASTFETCH_HEAD = ('{\n  "$schema": '
                  '"https://github.com/fastfetch-cli/fastfetch/raw/dev/doc/json_schema.json",\n')


def fastfetch():
    def item(ident, name, blurb, tags, body):
        return {
            "id": "fetch-" + ident,
            "section": "fastfetch",
            "name": name,
            "blurb": blurb,
            "author": "Genesi",
            "tags": tags,
            "preview": {"kind": "terminal", "lines": body["preview"]},
            "actions": [{"action": "file",
                         "path": "~/.config/fastfetch/config.jsonc",
                         "text": body["text"]}],
        }

    compact = FASTFETCH_HEAD + """  "logo": { "type": "small", "padding": { "top": 1, "right": 2 } },
  "display": { "separator": "  " },
  "modules": [
    { "type": "title", "format": "{user-name}@{host-name}" },
    "separator",
    { "type": "os", "key": "sistema" },
    { "type": "kernel", "key": "kernel" },
    { "type": "wm", "key": "sessão" },
    { "type": "memory", "key": "memoria" },
    { "type": "uptime", "key": "ligado ha" }
  ]
}
"""
    full = FASTFETCH_HEAD + """  "logo": { "padding": { "top": 2, "right": 3 } },
  "display": { "separator": "  ", "color": { "keys": "green" } },
  "modules": [
    "title", "separator",
    { "type": "os", "key": "sistema" },
    { "type": "host", "key": "maquina" },
    { "type": "kernel", "key": "kernel" },
    { "type": "packages", "key": "pacotes" },
    { "type": "shell", "key": "shell" },
    { "type": "wm", "key": "sessão" },
    { "type": "terminal", "key": "terminal" },
    { "type": "cpu", "key": "cpu" },
    { "type": "gpu", "key": "gpu" },
    { "type": "memory", "key": "memoria" },
    { "type": "disk", "key": "disco" },
    { "type": "uptime", "key": "ligado ha" },
    "break", "colors"
  ]
}
"""
    bare = FASTFETCH_HEAD + """  "logo": { "type": "none" },
  "display": { "separator": " " },
  "modules": [
    { "type": "custom", "format": "  genesi" },
    { "type": "os", "key": " " },
    { "type": "kernel", "key": " " },
    { "type": "memory", "key": " " },
    { "type": "uptime", "key": " " }
  ]
}
"""
    green = FASTFETCH_HEAD + """  "logo": { "source": "arch", "color": { "1": "green", "2": "green" } },
  "display": { "separator": "  ", "color": { "keys": "green", "title": "green" } },
  "modules": [
    { "type": "title", "format": "{user-name} em {host-name}" },
    { "type": "custom", "format": "\\u001b[32m-----------------------------\\u001b[0m" },
    { "type": "os", "key": "sistema" },
    { "type": "wm", "key": "sessão" },
    { "type": "cpu", "key": "cpu" },
    { "type": "memory", "key": "memoria" },
    { "type": "disk", "key": "disco" },
    { "type": "uptime", "key": "ligado ha" }
  ]
}
"""
    return [
        item("compact", "Compacto", "Cinco linhas e o logo pequeno.",
             ["curto"], {"text": compact,
                         "preview": ["matheus@genesi", "sistema  Genesi OS",
                                     "sessao   Hyprland", "memoria  6.2 / 16 GiB"]}),
        item("full", "Completo", "Tudo que dá para contar sobre a máquina.",
             ["longo"], {"text": full,
                         "preview": ["sistema  Genesi OS x86_64",
                                     "cpu      Ryzen 7 / 16 threads",
                                     "gpu      RTX 3050", "disco    712 / 954 GiB"]}),
        item("bare", "Sem logo", "Só texto, para quem abre muitos terminais.",
             ["minimalista"], {"text": bare,
                               "preview": ["  genesi", "  Genesi OS",
                                           "  6.14.2", "  1d 3h"]}),
        item("green", "Verde", "As cores da casa no prompt.",
             ["verde"], {"text": green,
                         "preview": ["matheus em genesi",
                                     "-----------------------------",
                                     "sistema  Genesi OS", "sessao   Hyprland"]}),
    ]


def rices(previous):
    """A whole desktop at once: colours, wallpaper, bar and lock together."""
    def rice(ident, name, blurb, tags, scheme, wall, bar, lock, colour):
        return {
            "id": "rice-" + ident,
            "section": "rices",
            "name": name,
            "blurb": blurb,
            "author": "Genesi",
            "tags": tags,
            "preview": {"kind": "rice", "accent": colour,
                        "wallpaper": "wall-" + wall},
            "includes": ["theme-" + scheme, "wall-" + wall, "bar-" + bar,
                         "lock-" + lock],
            "actions": [],
        }

    made = [
        rice("floresta-viva", "Floresta Viva",
             "Verde fechado, barra rente, bloqueio desfocado.",
             ["verde", "natureza"], "everforest-medium-dark", "forest-dark",
             "borda", "wallpaper", "#a7c080"),
        rice("orvalho", "Orvalho",
             "Verde claro da casa sobre água parada.",
             ["verde", "calmo"], "caelestia-default-dark", "lake",
             "arejado", "clean", "#8fd6ab"),
        rice("noite-baixa", "Noite Baixa",
             "Preto real, barra fina, nada brilhando.",
             ["escuro", "oled"], "darkgreen-hard-dark", "oled-mountains",
             "fio", "night", "#4f8f6a"),
        rice("terra", "Terra",
             "Gruvbox, cidade retrô e barra densa.",
             ["quente", "retro"], "gruvbox-medium-dark", "gruvbox-city",
             "painel", "terminal", "#d79921"),
        rice("meia-noite", "Meia-Noite",
             "Tokyo Night com neon e barra centralizada.",
             ["escuro", "neon"], "tokyonight-medium-dark", "neocity",
             "centrado", "night", "#7aa2f7"),
        rice("papel", "Papel",
             "Claro, quieto, para trabalhar de dia.",
             ["claro", "minimalista"], "catppuccin-latte-light", "minimal-c",
             "limpo", "clean", "#8839ef"),
    ]
    return made


def bundles():
    """Two or three things that go together, and say what they will change."""
    return [
        {
            "id": "bundle-primeira-troca",
            "section": "bundles",
            "name": "Primeira Troca",
            "blurb": "O básico para o desktop deixar de ser o padrão: cor, "
                     "papel de parede e uma barra que respira.",
            "author": "Genesi",
            "tags": ["comeco"],
            "preview": {"kind": "rice", "accent": "#8fd6ab",
                        "wallpaper": "wall-nature"},
            "includes": ["theme-caelestia-default-dark", "wall-nature",
                         "bar-arejado"],
            "actions": [],
        },
        {
            "id": "bundle-terminal",
            "section": "bundles",
            "name": "Vida no Terminal",
            "blurb": "Fastfetch completo, bloqueio monoespaçado e uma barra "
                     "densa: para quem vive no prompt.",
            "author": "Genesi",
            "tags": ["terminal"],
            "preview": {"kind": "rice", "accent": "#8fd6ab",
                        "wallpaper": "wall-ink-wave"},
            "includes": ["fetch-full", "lock-terminal", "bar-informativo",
                         "wall-ink-wave"],
            "actions": [],
        },
        {
            "id": "bundle-descanso",
            "section": "bundles",
            "name": "Descanso",
            "blurb": "Claro de dia, sem barulho visual: tema claro, papel "
                     "minimalista e barra limpa.",
            "author": "Genesi",
            "tags": ["claro", "calmo"],
            "preview": {"kind": "rice", "accent": "#40a02b",
                        "wallpaper": "wall-minimal-c"},
            "includes": ["theme-everforest-medium-light", "wall-minimal-c",
                         "bar-limpo"],
            "actions": [],
        },
    ]


if __name__ == "__main__":
    build()
