#!/usr/bin/env python3
"""
build-catalog.py — writes catalog/catalog.json, and is the reason it can be
trusted.

The catalogue is DATA: every item is a name, a picture and a list of actions
out of the vocabulary genesi-store implements. Nothing in it is code. But the
picture comes from somewhere, and "somewhere" is the part that rots -- links
die, files are replaced, repositories are renamed. So the catalogue is not
hand-written: it is generated by this script, which

  * fetches every wallpaper it lists and records the SIZE and the SHA-256 it
    got, so the store can refuse a file that changed under it;
  * reads caelestia's own scheme files to get the colours each theme card is
    painted in, rather than a person retyping thirty palettes;
  * fails loudly on a link that does not answer, so a dead item is a build
    failure here instead of a broken card on somebody's desktop.

Re-run it when adding items, or to refresh what the links serve:

    python3 build-catalog.py            # verify and write
    python3 build-catalog.py --offline  # rebuild the text-only items

Sources, and why these: the wallpapers come from one MIT-licensed collection
(D3Ext/aesthetic-wallpapers), so there is a single licence to honour and a
single repository to check rather than twenty. The colour schemes come from
caelestia-cli, which is already installed -- applying one downloads nothing at
all. The bar arrangements are Genesi's own presets, already shipped.
"""
import hashlib
import io
import json
import os
import re
import sys
import tempfile
import time
import urllib.error
import urllib.parse
import urllib.request

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "catalog", "catalog.json")
OFFLINE = "--offline" in sys.argv

WALL_REPO = "https://raw.githubusercontent.com/D3Ext/aesthetic-wallpapers/main/images/"
SCHEME_REPO = ("https://raw.githubusercontent.com/caelestia-dots/cli/main/"
               "src/caelestia/data/schemes/")

SECTIONS = [
    {"id": "discover", "label": "Descobrir", "label_en": "Discover",
     "icon": "home", "blurb": "O que vale a pena hoje."},
    {"id": "rices", "label": "Ambientes", "label_en": "Rices", "icon": "grid",
     "blurb": "Um desktop inteiro, de uma vez."},
    {"id": "themes", "label": "Temas", "label_en": "Themes", "icon": "palette",
     "blurb": "A cor de tudo, do topo ao terminal."},
    # These were one shelf, and the blurb on it said "the session one and the
    # login one, which are two" -- a label apologising for the shelf it was
    # on. They are two different programs, at two different moments, and only
    # one of them can lock you out of the machine.
    {"id": "login", "label": "Tela de login", "label_en": "Login screens",
     "icon": "login", "blurb": "Antes de entrar: o que pede sua senha no boot."},
    {"id": "lockscreens", "label": "Bloqueio da sessão", "label_en": "Lockscreens",
     "icon": "lock",
     "blurb": "Já dentro: a tranca do caelestia, que segue o seu tema e "
              "o seu papel de parede."},
    {"id": "bars", "label": "Barras", "label_en": "Bar styles", "icon": "bar",
     "blurb": "Quinze arranjos da barra."},
    {"id": "fastfetch", "label": "Fastfetch", "label_en": "Fastfetch",
     "icon": "terminal", "blurb": "O cartão de visita do terminal."},
    {"id": "decor", "label": "Decoração", "label_en": "Decor", "icon": "image",
     "blurb": "Papéis de parede e detalhes."},
    {"id": "bundles", "label": "Coleções", "label_en": "Bundles", "icon": "box",
     "blurb": "Combinações que já vêm casadas."},
    {"id": "plugins", "label": "Plugins", "label_en": "Plugins", "icon": "plug",
     "blurb": "Partes do desktop que vêm desligadas até você querer."},
]

# ── Plugins ────────────────────────────────────────────────────────────────
# Parts of the shell that ship inside genesi-caelestia-shell and stay off
# until one of these cards switches them on. Switching one on is WRITING A
# FILE -- ~/.config/genesi/plugins/<id>.json -- that the shell's
# GenesiPluginSwitch reads, and switching it off is the store's revert
# deleting it. So a plugin card is data like every other card here: the code
# it turns on is code a signed package already carries, and no card can name
# code of its own. ci/plugins-test.py checks that every plugin the shell asks
# about has a card here writing exactly the path it reads.
PLUGINS = [
    ("game-center", "Game Center",
     "Oito joguinhos rápidos no canto inferior esquerdo da tela: Snake, "
     "2048, Flappy Leaf, Blocks, Breakout, Campo Minado, Memória e Simon.",
     ["jogos", "canto"], "plugin-game-center.jpg"),
    ("leaf", "Folhinha",
     "Um bichinho na sua tela que é o estado do PC: sua quando a CPU "
     "esquenta, dorme quando você sai e cresce com você.",
     ["bichinho", "sistema"], "plugin-leaf.jpg"),
    ("live-weather", "Clima vivo",
     "Quando chove lá fora, chove no seu papel de parede: chuva, neve, "
     "tempestade e neblina, por baixo das janelas.",
     ["clima", "papel de parede"], "plugin-live-weather.jpg"),
]


def plugin_path(ident):
    return "~/.config/genesi/plugins/%s.json" % ident

# ── Wallpapers ──────────────────────────────────────────────────────────────
# Chosen to lead with Genesi's own weather -- forest, water, green light --
# and then widen. The name is what a person reads; the file is what the link
# serves.
WALLS = [
    ("forest-dark", "dark_forest.png", "Floresta Escura",
     "Mata fechada ao anoitecer.", ["natureza", "escuro", "verde"]),
    ("nature", "nature.jpg", "Natureza",
     "Verde aberto, sem pressa.", ["natureza", "verde"]),
    ("everforest-robin", "everforest_robin.png", "Everforest",
     "A paleta everforest em desenho.", ["natureza", "verde", "arte"]),
    ("lake", "lake.jpg", "Lago",
     "Água parada e montanha.", ["natureza", "agua", "calmo"]),
    ("art-lake", "art-lake.png", "Lago Ilustrado",
     "O mesmo silêncio, desenhado.", ["arte", "agua", "calmo"]),
    ("mountains", "mountains.png", "Montanhas",
     "Camadas até o horizonte.", ["natureza", "minimalista"]),
    ("nord-city", "nord_dark_city.png", "Cidade Nord",
     "A cidade em nord, bem larga.", ["cidade", "escuro", "frio"]),
    ("oled-mountains", "oled-mountains.jpg", "Montanhas OLED",
     "Preto real, para telas OLED.", ["escuro", "oled", "minimalista"]),
    ("moon", "moon.png", "Lua",
     "Uma lua e nada mais.", ["escuro", "minimalista", "noite"]),
    ("falltree", "falltree.jpg", "Outono",
     "Uma árvore em queda de folhas.", ["natureza", "quente"]),
    ("green-sun", "green-sun.jpg", "Sol Verde",
     "Luz filtrada por folhas.", ["verde", "natureza"]),
    ("tree-castle", "tree-nature-castleinsky.png", "Castelo no Céu",
     "Árvore, castelo, nuvem.", ["arte", "natureza"]),
    ("ink-wave", "ink_wave.png", "Onda de Tinta",
     "Nanquim em movimento.", ["arte", "escuro", "minimalista"]),
    ("aurora", "aurora_v02.png", "Aurora",
     "Luz fria sobre o horizonte.", ["minimalista", "frio", "noite"]),
    ("minimal-c", "minimal_c.png", "Minimal",
     "Quase nada, bem colocado.", ["minimalista", "escuro"]),
    ("arch-nord", "arch-nord-dark.png", "Arch Nord",
     "O logo, em nord.", ["escuro", "frio", "arch"]),
    ("gruvbox-city", "gruvbox_retrocity.png", "Cidade Gruvbox",
     "Retro em terra e mostarda.", ["quente", "retro", "cidade"]),
    ("neocity", "neocity.png", "Neocidade",
     "Neon e chuva.", ["cidade", "escuro", "neon"]),
]

# ── Colour schemes ─────────────────────────────────────────────────────────
# (family, flavour, mode, name, blurb). Everything here ships with
# caelestia-cli, so applying one is instant and offline.
SCHEMES = [
    ("caelestia", "default", "dark", "Caelestia", "O tom da casa, no escuro."),
    ("caelestia", "default", "light", "Caelestia Claro", "O mesmo, na luz."),
    ("darkgreen", "hard", "dark", "Verde Profundo", "Quase preto, com seiva."),
    ("darkgreen", "medium", "dark", "Verde Mata", "Verde sem gritar."),
    ("everforest", "medium", "dark", "Everforest", "Musgo, pedra e madeira."),
    ("everforest", "hard", "dark", "Everforest Duro", "O mesmo, com mais contraste."),
    ("everforest", "medium", "light", "Everforest Claro", "Papel e folha."),
    ("everblush", "medium", "dark", "Everblush", "Escuro com um rubor."),
    ("catppuccin", "mocha", "dark", "Catppuccin Mocha", "O pastel que todo mundo conhece."),
    ("catppuccin", "macchiato", "dark", "Catppuccin Macchiato", "Um passo mais claro."),
    ("catppuccin", "frappe", "dark", "Catppuccin Frappe", "Meio do caminho."),
    ("catppuccin", "latte", "light", "Catppuccin Latte", "Claro, sem estourar."),
    ("gruvbox", "medium", "dark", "Gruvbox", "Terra, mostarda e ferrugem."),
    ("gruvbox", "hard", "dark", "Gruvbox Duro", "Fundo mais fechado."),
    ("gruvbox", "soft", "dark", "Gruvbox Macio", "Fundo mais aberto."),
    ("gruvbox", "medium", "light", "Gruvbox Claro", "O mesmo, de dia."),
    ("nord", "medium", "dark", "Nord", "Gelo e aço."),
    ("tokyonight", "medium", "dark", "Tokyo Night", "Cidade às três da manhã."),
    ("rosepine", "main", "dark", "Rose Pine", "Vinho e pinho."),
    ("rosepine", "moon", "dark", "Rose Pine Moon", "Um pouco mais alto."),
    ("rosepine", "dawn", "light", "Rose Pine Dawn", "O amanhecer da mesma."),
    ("dracula", "medium", "dark", "Dracula", "Roxo clássico."),
    ("onedark", "default", "dark", "One Dark", "O tema de editor virou desktop."),
    ("oldworld", "default", "dark", "Old World", "Sepia e quieto."),
    ("solarized", "medium", "dark", "Solarized", "O mais estudado de todos."),
    ("shadotheme", "default", "dark", "Shado", "Cinza com um fio de cor."),
]

# ── Bar arrangements ───────────────────────────────────────────────────────
# Genesi's own presets, already installed by genesi-caelestia-settings.
BARS = [
    ("10-padrao", "Padrão", "A barra como o caelestia entrega."),
    ("15-borda", "Rente", "Sem moldura: encostada na borda da tela."),
    ("20-centrado", "Centralizado", "Logo em cima, espaços no meio, o resto embaixo."),
    ("25-fio", "Fio", "O mais estreito que dá para acertar com o mouse."),
    ("30-ilha", "Ilha", "Cantos bem redondos, barra na beirada."),
    ("40-numeros", "Numeros", "Espaços de trabalho numerados."),
    ("45-arejado", "Arejado", "Mais espaço entre tudo."),
    ("50-janelas", "Janelas", "Mostra as janelas abertas."),
    ("55-painel", "Painel", "Denso, como um painel de controle."),
    ("60-informativo", "Informativo", "Tudo que dá para medir, medido."),
    ("70-compacto", "Compacto", "O essencial, junto."),
    ("80-limpo", "Limpo", "So o necessario."),
    ("85-relogio", "Relogio", "O relógio em primeiro lugar."),
    ("90-trilha", "Trilha", "Uma linha contínua."),
    ("95-oculta", "Oculta", "Some até você precisar."),
]


# Where build-time downloads are kept between runs. Outside the repository,
# because it is scratch: describing the qylock collection means fetching ~570
# MB of theme, and a build that pays that again to change one blurb is a build
# nobody runs twice. Delete it to force a fresh fetch.
CACHE = os.path.join(tempfile.gettempdir(), "genesi-store-build-cache")


def get(url, binary=False):
    cached = os.path.join(CACHE, hashlib.sha256(url.encode("utf-8")).hexdigest())
    if os.path.exists(cached):
        with open(cached, "rb") as fh:
            data = fh.read()
        return data if binary else data.decode("utf-8")
    request = urllib.request.Request(url, headers={"User-Agent": "genesi-store-build"})
    # Some of these are fourteen-megabyte backgrounds, and describing a whole
    # collection is hundreds of requests -- at that volume a read timing out
    # is not an error, it is Tuesday. Three tries, longer each time.
    data = None
    for attempt in range(3):
        try:
            with urllib.request.urlopen(request, timeout=60 * (attempt + 1)) as response:
                data = response.read()
            break
        except (urllib.error.URLError, OSError) as exc:
            if attempt == 2:
                raise SystemExit("could not fetch %s: %s" % (url, exc))
            sys.stderr.write("  retrying %s (%s)\n"
                             % (url.rsplit("/", 1)[-1], exc))
            time.sleep(2 * (attempt + 1))
    os.makedirs(CACHE, exist_ok=True)
    tmp = cached + ".part"
    with open(tmp, "wb") as fh:
        fh.write(data)
    os.replace(tmp, cached)
    return data if binary else data.decode("utf-8")


def scheme_colours(family, flavour, mode):
    """The five colours a theme card is painted in, from caelestia's own file."""
    url = "%s%s/%s/%s.txt" % (SCHEME_REPO, family, flavour, mode)
    want = ("background", "onBackground", "primary", "secondary", "tertiary",
            "surface")
    found = {}
    for line in get(url).splitlines():
        parts = line.split()
        if len(parts) == 2 and parts[0] in want:
            found[parts[0]] = "#" + parts[1].lower()
    missing = [k for k in want if k not in found]
    if missing:
        raise SystemExit("scheme %s/%s/%s has no %s"
                         % (family, flavour, mode, ", ".join(missing)))
    return found


def thumbnail(ident, data, filename):
    """A small picture of the wallpaper, shipped IN the package.

    Without this a decor card is a grey rectangle with a file size in it until
    somebody downloads the wallpaper -- which is backwards, because the picture
    is the reason to download it. 480px of JPEG is about 25 kB, so eighteen of
    them cost less than half a megabyte and the shelf becomes a shelf of
    pictures. They are also what the lock screens, the rices and the
    collections are drawn over, so one download feeds four shelves.
    """
    from PySide6.QtGui import QGuiApplication, QImage
    from PySide6.QtCore import Qt
    global _APP
    try:
        _APP
    except NameError:
        _APP = QGuiApplication([])
    image = QImage.fromData(data)
    if image.isNull():
        raise SystemExit("could not read %s as an image" % filename)
    # 480 was chosen when a card was a small tile in a grid. The shelf is a
    # mosaic now: a wide card is most of the window, and the detail sheet
    # draws the same picture across the top of it. On a 1900px window that was
    # a 480px JPEG stretched nearly four times, which looks exactly as bad as
    # it sounds.
    #
    # 1280 covers the widest card on a 4K screen without being a second copy
    # of the wallpaper: these stay around 120 kB each.
    small = image.scaledToWidth(1280, Qt.SmoothTransformation)
    out = os.path.join(HERE, "catalog", "thumbs")
    os.makedirs(out, exist_ok=True)
    name = ident + ".jpg"
    if not small.save(os.path.join(out, name), "JPG", 82):
        raise SystemExit("could not write the thumbnail for " + ident)
    return name


MIN_WALL_WIDTH = 1920


def wallpaper_size(data):
    """The pixel size of a downloaded wallpaper, or (0, 0) if unreadable."""
    from PySide6.QtGui import QGuiApplication, QImage
    global _APP
    try:
        _APP
    except NameError:
        _APP = QGuiApplication([])
    image = QImage.fromData(data)
    return image.width(), image.height()


def wallpaper_asset(filename):
    url = WALL_REPO + filename
    data = get(url, binary=True)
    kind = "image/png" if filename.endswith(".png") else "image/jpeg"
    head = {"image/png": b"\x89PNG", "image/jpeg": b"\xff\xd8\xff"}[kind]
    if not data.startswith(head):
        raise SystemExit("%s is not %s -- the link is broken" % (url, kind))
    width, height = wallpaper_size(data)
    if width and width < MIN_WALL_WIDTH:
        raise SystemExit("%s is only %dx%d; a wallpaper this shelf offers has "
                         "to be at least %d wide or it is scaled up on every "
                         "machine Genesi installs on"
                         % (filename, width, height, MIN_WALL_WIDTH))
    # The bytes come back too: the thumbnail is made from the file we just
    # verified, not from a second download of something that may differ.
    return ({"url": url, "type": kind, "bytes": len(data),
             "width": width, "height": height,
             "sha256": hashlib.sha256(data).hexdigest()}, data)


# ── Two languages, English first ───────────────────────────────────────────
#
# The tables in this file are written in Portuguese because that is the
# language the shelf was designed in and the one the copy was tuned in. What
# SHIPS leads with English, because the store is part of an operating system
# people install from anywhere, and falls back to the machine's own language
# when it has one.
#
# So every card carries both: `name` and `blurb` are English, `name_pt` and
# `blurb_pt` are what is written below. The app picks by locale.
#
# The translations live in one file rather than inline in each table so that
# adding a card does not mean editing two places -- and so that the check
# below can be exhaustive: a string with no translation FAILS THE BUILD
# rather than shipping half-translated, which is the state every
# half-internationalised app is permanently stuck in.
from catalog_en import ENGLISH, SAME  # noqa: E402


def englished(text, what):
    if text is None or text == "":
        return text
    if text in SAME:
        return text
    if text not in ENGLISH:
        MISSING.add("%s: %r" % (what, text))
        return text
    return ENGLISH[text]


MISSING = set()


def bilingual(item):
    """Return the item with English up front and Portuguese beside it."""
    out = dict(item)
    for field in ("name", "blurb"):
        if field in out:
            out[field + "_pt"] = out[field]
            out[field] = englished(out[field], field)
    if out.get("tags"):
        out["tags_pt"] = list(out["tags"])
        out["tags"] = [englished(t, "tag") for t in out["tags"]]
    return out


def bilingual_section(section):
    out = dict(section)
    out["label_pt"] = out["label"]
    # These already carried an English label; use it and drop the duplicate.
    out["label"] = out.pop("label_en", None) or englished(out["label"], "label")
    if "blurb" in out:
        out["blurb_pt"] = out["blurb"]
        out["blurb"] = englished(out["blurb"], "section blurb")
    return out


def build():
    previous = {}
    if os.path.exists(OUT):
        with io.open(OUT, encoding="utf-8") as fh:
            for item in json.load(fh).get("items", []):
                previous[item["id"]] = item

    items = []

    # ── Themes ─────────────────────────────────────────────────────────────
    for family, flavour, mode, name, blurb in SCHEMES:
        ident = "theme-%s-%s-%s" % (family, flavour, mode)
        # Offline reuses the COLOURS, which came off the network, and rebuilds
        # the item around them. Reusing the whole item meant a change to a name
        # or a tag silently did not happen on an offline build.
        if OFFLINE and ident in previous:
            colours = {"background": previous[ident]["preview"]["background"],
                       "onBackground": previous[ident]["preview"]["ink"],
                       "surface": previous[ident]["preview"].get("surface", previous[ident]["preview"]["background"]),
                       "primary": previous[ident]["preview"]["colours"][0],
                       "secondary": previous[ident]["preview"]["colours"][1],
                       "tertiary": previous[ident]["preview"]["colours"][2]}
        else:
            colours = scheme_colours(family, flavour, mode)
        items.append({
            "id": ident,
            "section": "themes",
            "name": name,
            "blurb": blurb,
            "author": "caelestia / %s" % family,
            "mode": mode,
            "tags": ["escuro" if mode == "dark" else "claro", family],
            "preview": {"kind": "scheme",
                        "background": colours["background"],
                        "surface": colours.get("surface", colours["background"]),
                        "ink": colours["onBackground"],
                        "colours": [colours["primary"], colours["secondary"],
                                    colours["tertiary"]]},
            "actions": [{"action": "scheme", "name": family,
                         "flavour": flavour, "mode": mode}],
        })

    # ── Decor: wallpapers ──────────────────────────────────────────────────
    for ident, filename, name, blurb, tags in WALLS:
        full = "wall-" + ident
        thumb = full + ".jpg"
        have_thumb = os.path.exists(os.path.join(HERE, "catalog", "thumbs", thumb))
        if OFFLINE and full in previous and have_thumb:
            asset = previous[full]["assets"]["picture"]
        else:
            asset, raw = wallpaper_asset(filename)
            thumb = thumbnail(full, raw, filename)
        items.append({
            "id": full,
            "section": "decor",
            "name": name,
            "blurb": blurb,
            "author": "D3Ext/aesthetic-wallpapers",
            "license": "MIT",
            "source": "https://github.com/D3Ext/aesthetic-wallpapers",
            "tags": tags,
            "preview": {"kind": "image", "thumb": thumb, "asset": "picture"},
            "assets": {"picture": asset},
            "actions": [{"action": "wallpaper", "asset": "picture"}],
        })

    # ── Bar styles ─────────────────────────────────────────────────────────
    for preset, name, blurb in BARS:
        items.append({
            "id": "bar-" + preset.split("-", 1)[1],
            "section": "bars",
            "name": name,
            "blurb": blurb,
            "author": "Genesi",
            "tags": ["barra"],
            "preview": dict({"kind": "bar", "preset": preset},
                            **bar_shape(preset)),
            "actions": [{"action": "bar", "preset": preset}],
        })

    for extra in (lockscreens(), fastfetch(), rices(previous), bundles(),
                  plugins(), factory()):
        items.extend(extra)

    # The login screens that are downloaded rather than shipped. The map they
    # point into is what makes them data: a card carries a key, and the key
    # resolves -- in the store, and again in the helper, out of the copy under
    # /usr/share that only root can write -- to a URL, a digest and a
    # destination this build decided.
    greeter_specs = {}
    if OFFLINE:
        if os.path.exists(OUT):
            with io.open(OUT, encoding="utf-8") as fh:
                old = json.load(fh)
            greeter_specs = old.get("greeters") or {}
            # Those items were written out bilingual -- English in `name`,
            # Portuguese in `name_pt` -- and bilingual() below translates
            # `name` again. Put them back the way the tables write them, or
            # every reused login screen is an English string with "no
            # English" and the offline build cannot finish.
            for i in old.get("items", []):
                if not any(a.get("action") == "greeter"
                           for a in i.get("actions", [])):
                    continue
                i = dict(i)
                for field in ("name", "blurb", "tags"):
                    if field + "_pt" in i:
                        i[field] = i.pop(field + "_pt")
                items.append(i)
    else:
        greeter_specs, greeter_items = greeters()
        items.extend(greeter_items)

    # English up front, Portuguese beside it. A string with no translation
    # stops the build rather than shipping a shelf that is half one language
    # and half the other.
    data = {
        "version": 1,
        "updated": time.strftime("%Y-%m-%d"),
        "sections": [bilingual_section(x) for x in SECTIONS],
        "greeters": greeter_specs,
        "items": [bilingual(i) for i in items],
    }
    if MISSING:
        raise SystemExit("no English for %d string(s):\n  %s"
                         % (len(MISSING),
                            "\n  ".join(sorted(MISSING)[:12])))

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with io.open(OUT, "w", encoding="utf-8", newline="\n") as fh:
        json.dump(data, fh, indent=1, ensure_ascii=False, sort_keys=False)
        fh.write("\n")
    print("catalog: %d items across %d sections" % (len(items), len(SECTIONS)))
    for section in SECTIONS:
        count = len([i for i in items if i["section"] == section["id"]])
        print("  %-12s %d" % (section["id"], count))


# ── The text-only shelves ──────────────────────────────────────────────────


def plugins():
    """One card per plugin. Each writes its own switch file and nothing else,
    so two plugins never share a slot and turning one on never turns another
    off."""
    return [{
        "id": "plugin-" + ident,
        "section": "plugins",
        "name": name,
        "blurb": blurb,
        "author": "Genesi",
        "tags": tags,
        "preview": {"kind": "image", "thumb": thumb},
        "actions": [{"action": "file", "path": plugin_path(ident),
                     "text": '{"enabled": true}\n'}],
    } for ident, name, blurb, tags, thumb in PLUGINS]



def lockscreens():
    out = []
    # There are no session-lock looks on this shelf any more, and that is
    # deliberate. caelestia locks the session itself -- its IdleMonitors
    # answer logind's Lock signal directly -- so the only way to put hyprlock
    # there was to start a SECOND locker on the same single-holder Wayland
    # protocol, and that crashed the shell on unlock. What the session lock
    # looks like is your theme and your wallpaper; those shelves set it.

    # ── The other lock: the screen BEFORE the session ──────────────────────
    #
    # Different machinery entirely -- SDDM, running as root, before anyone has
    # logged in -- so these are their own family, and the app says so. Only
    # themes that are already installed are offered: a login screen pointed at
    # a theme that is not there is a login screen that does not come up, and
    # that is not a thing to find out by rebooting.
    # Genesi's own, whose picture is a render of the very QML this package
    # installs -- made by ci/sddm-shot, kept in sddm/preview.png, which is also
    # the Screenshot= the theme's metadata has always claimed to have.
    #
    # And Breeze, which is not really a theme here: it is the way OUT. Picking
    # it deletes the drop-in, so the login screen goes back to whatever the
    # system decides rather than to whatever this tool last saw.
    #
    # SDDM's other stock themes used to be on this shelf and are not any more.
    # They shipped no picture, so they were grey cards among thirty with real
    # screenshots -- and a grey card is the thing this whole shelf was rebuilt
    # to stop being.
    genesi_shot = os.path.join(HERE, "sddm", "preview.png")
    thumb = ""
    if os.path.exists(genesi_shot):
        with io.open(genesi_shot, "rb") as fh:
            thumb = thumbnail("greeter-genesi", fh.read(), "preview.png")
    for ident, theme, name, blurb, preview in (
            ("genesi", "genesi", "Genesi",
             "A nossa: a marca, a hora e um campo só. Vem com a loja.",
             {"kind": "login", "theme": "genesi", "background": "#070c09",
              "accent": "#39d98a", "thumb": thumb}),
            ("breeze", "breeze", "A padrão do sistema",
             "Volta para a tela que o Genesi instala. É o caminho de volta "
             "de qualquer uma das outras.",
             {"kind": "login", "theme": "breeze", "background": "#1b1e20",
              "accent": "#8ab4d8"})):
        out.append({
            "id": "login-" + ident,
            "section": "login",
            "name": name,
            "blurb": blurb,
            "family": "login",
            "author": "Genesi" if theme == "genesi" else "SDDM",
            "tags": ["login", "antes da sessão"],
            "needs_root": True,
            "preview": preview,
            "actions": [{"action": "login", "theme": theme}],
        })
    return out


# Pictures worth putting on a terminal. Chosen to be different from each
# other rather than to be the prettiest: a neon city, an ink wave, a castle,
# a moon. One card each.
FETCH_PICTURES = [
    ("neon", "neocity.png", "neon", ["cidade", "escuro"]),
    ("tinta", "ink_wave.png", "tinta", ["arte", "minimalista"]),
    ("castelo", "tree-nature-castleinsky.png", "castelo", ["arte", "natureza"]),
    ("lua", "moon.png", "lua", ["escuro", "noite"]),
    ("gruvbox", "gruvbox_retrocity.png", "gruvbox", ["retro", "quente"]),
]

# The Genesi leaf, the same file the packaged default uses, so the store's
# fancy layout and the one the machine ships with draw the same logo.
GENESI_LOGO_BLOCK = """  "logo": {
    "type": "file",
    "source": "/usr/share/genesi/fastfetch/genesi-logo.txt",
    "color": { "1": "38;2;29;158;117", "2": "38;2;225;245;238" },
    "padding": { "top": 1, "right": 3, "left": 2 }
  },
"""

SIXEL_LOGO_BLOCK = """  "logo": {
    "type": "sixel",
    "source": "{{asset:picture}}",
    "width": 30,
    "padding": { "top": 1, "right": 3 }
  },
"""

IMAGE_BLURB = ("Uma foto no lugar do desenho, em sixel. Precisa de um "
               "terminal que desenhe imagens: o foot, que é o padrão "
               "do Genesi, desenha.")


FASTFETCH_HEAD = ('{\n  "$schema": '
                  '"https://github.com/fastfetch-cli/fastfetch/raw/dev/doc/json_schema.json",\n')


BAR_PRESET_DIR = os.path.join(
    os.path.dirname(HERE), "genesi-caelestia-settings", "bar-presets")


def bar_shape(preset):
    """What one bar preset actually looks like, read from the preset itself.

    Fifteen cards drawn from one generic picture are fifteen identical cards,
    which is what this shelf was: you could not tell the thin one from the
    wide one, or the one with a clock at the top from the one with a logo.
    Everything needed to tell them apart is already in the preset file --
    which modules, in what order, how wide, how far apart, whether things sit
    on pills -- so the picture is read from there rather than invented.

    Read at BUILD time, not by the app: the app would have to go find the
    settings package at runtime, and a card that cannot draw itself without
    another package installed is a card that is blank on somebody's machine.
    """
    path = os.path.join(BAR_PRESET_DIR, preset + ".json")
    if not os.path.exists(path):
        raise SystemExit("the bar preset %s is not in %s" % (preset, BAR_PRESET_DIR))
    with io.open(path, encoding="utf-8") as fh:
        data = json.load(fh)
    bar = data.get("bar", data)
    entries = [e.get("id") for e in (bar.get("entries") or []) if e.get("id")]
    if not entries:
        raise SystemExit("the bar preset %s lists no modules" % preset)

    def opt(name, key):
        block = bar.get(name)
        return bool(isinstance(block, dict) and block.get(key))

    # Deliberately NOT width or spacing. Those were in the presets and are not
    # caelestia bar properties at all -- there is no such key in BarConfig,
    # and the bar's thickness comes from the appearance tokens. So the cards
    # were drawing a thin bar and a wide bar for two presets that produce
    # exactly the same bar, which is a picture telling a lie about what the
    # button does. What is left is what genuinely differs.
    return {
        "entries": entries,
        "pills": opt("clock", "background") or opt("tray", "background"),
        "date": opt("clock", "showDate"),
        "windows": opt("workspaces", "showWindows"),
        "trail": opt("workspaces", "activeTrail"),
        "occupied": opt("workspaces", "occupiedBg"),
        "audio": opt("status", "showAudio"),
        "compact": opt("activeWindow", "compact") or opt("tray", "compact"),
        # persistent:false is the auto-hiding one. showOnHover alone is the
        # default and does not hide anything.
        "hidden": bar.get("persistent") is False,
    }


def factory():
    """One card per shelf that puts it back the way the machine shipped.

    Revert, on an item's page, undoes THAT item -- it needs to know what was
    there before, so it only exists for something the store itself applied.
    That is the wrong tool for "I have been clicking around for an hour and I
    want my desktop back", which is the state somebody is actually in when
    they go looking for this.

    So these undo the CATEGORY, from whatever it is now, without needing to
    remember how it got there. For the shelves that are a config file, factory
    means deleting the file the store wrote: the packaged default is what gets
    read once nothing is overriding it, which is the same thing a fresh
    install has.

    Deliberately not on Decoration: there is no single wallpaper the machine
    ships with, so a card promising one would be making it up.
    """
    def card(ident, section, name, blurb, preview, actions, needs_root=False):
        card = {
            "id": "default-" + ident,
            "section": section,
            "name": name,
            "blurb": blurb,
            "family": "factory",
            "author": "Genesi",
            "tags": ["padrão", "de fábrica"],
            "preview": preview,
            "actions": actions,
        }
        # Putting the login screen back is still changing /etc, so it still
        # asks for a password and the card still has to say so.
        if needs_root:
            card["needs_root"] = True
        return card

    plain = {"kind": "scheme", "colours": ["#39d98a", "#8fd6ab", "#1d2a22"],
             "background": "#0c120f", "surface": "#16211b", "ink": "#e9f5ee"}

    return [
        card("themes", "themes", "Como vem de fábrica",
             "A paleta que segue o seu papel de parede, que é a do Genesi novo.",
             plain, [{"action": "scheme", "name": "dynamic"}]),

        card("login", "login", "Como vem de fábrica",
             "A tela de login do Genesi, sem nada baixado por cima.",
             {"kind": "login", "theme": "genesi", "accent": "#39d98a"},
             [{"action": "login", "theme": "genesi"}], needs_root=True),

        # Deleting the file is the whole undo: with no hyprlock.conf of its
        # own the machine is back to having no session lock configured, and
        # `unlocker` stops the watcher the store started.
        card("lockscreens", "lockscreens", "Como vem de fábrica",
             "A tranca do próprio caelestia, que segue o seu tema e o seu "
             "papel de parede.",
             {"kind": "lock", "accent": "#8fd6ab", "background": "#0c120f"},
             [{"action": "unlocker"}]),

        card("fastfetch", "fastfetch", "Como vem de fábrica",
             "Volta para o cartão do Genesi que aparece ao abrir o terminal.",
             {"kind": "terminal",
              "lines": ["genesi@genesi", "sistema  Genesi OS",
                        "sessão   Hyprland"]},
             [{"action": "restore",
               "path": "~/.config/fastfetch/config.jsonc"}]),

        # Every plugin off: each switch file deleted, which is the state a
        # new machine is in.
        card("plugins", "plugins", "Como vem de fábrica",
             "Nenhum plugin ligado: o desktop como o Genesi entrega.",
             plain,
             [{"action": "restore", "path": plugin_path(ident)}
              for ident, *_ in PLUGINS]),

        card("bars", "bars", "Como vem de fábrica",
             "O arranjo de barra que vem no Genesi novo.",
             {"kind": "bar", "background": "#0c120f", "surface": "#16211b",
              "ink": "#e9f5ee", "accent": "#39d98a"},
             [{"action": "bar", "preset": "10-padrao"}]),
    ]


def fastfetch():
    def item(ident, name, blurb, tags, body):
        out = {
            "id": "fetch-" + ident,
            "section": "fastfetch",
            "name": name,
            "blurb": blurb,
            "author": "Genesi",
            "tags": tags,
            # The logo is the biggest difference between one fastfetch and the
            # next, and the card was not drawing it at all -- so four options
            # that look nothing alike in a terminal looked identical here.
            "preview": {"kind": "terminal", "lines": body["preview"],
                        "logo": body.get("logo", "full"),
                        "keyed": body.get("keyed", True)},
            "actions": [{"action": "file",
                         "path": "~/.config/fastfetch/config.jsonc",
                         "text": body["text"]}],
        }
        if body.get("asset"):
            out["assets"] = {"picture": body["asset"]}
        return out

    compact = FASTFETCH_HEAD + """  "logo": { "type": "small", "padding": { "top": 1, "right": 2 } },
  "display": { "separator": "  " },
  "modules": [
    { "type": "title", "format": "{user-name}@{host-name}" },
    "separator",
    { "type": "os", "key": "sistema" },
    { "type": "kernel", "key": "kernel" },
    { "type": "wm", "key": "sessão" },
    { "type": "memory", "key": "memoria" },
    { "type": "uptime", "key": "ligado ha" }
  ]
}
"""
    full = FASTFETCH_HEAD + """  "logo": { "padding": { "top": 2, "right": 3 } },
  "display": { "separator": "  ", "color": { "keys": "green" } },
  "modules": [
    "title", "separator",
    { "type": "os", "key": "sistema" },
    { "type": "host", "key": "maquina" },
    { "type": "kernel", "key": "kernel" },
    { "type": "packages", "key": "pacotes" },
    { "type": "shell", "key": "shell" },
    { "type": "wm", "key": "sessão" },
    { "type": "terminal", "key": "terminal" },
    { "type": "cpu", "key": "cpu" },
    { "type": "gpu", "key": "gpu" },
    { "type": "memory", "key": "memoria" },
    { "type": "disk", "key": "disco" },
    { "type": "uptime", "key": "ligado ha" },
    "break", "colors"
  ]
}
"""
    bare = FASTFETCH_HEAD + """  "logo": { "type": "none" },
  "display": { "separator": " " },
  "modules": [
    { "type": "custom", "format": "  genesi" },
    { "type": "os", "key": " " },
    { "type": "kernel", "key": " " },
    { "type": "memory", "key": " " },
    { "type": "uptime", "key": " " }
  ]
}
"""
    green = FASTFETCH_HEAD + """  "logo": { "source": "arch", "color": { "1": "green", "2": "green" } },
  "display": { "separator": "  ", "color": { "keys": "green", "title": "green" } },
  "modules": [
    { "type": "title", "format": "{user-name} em {host-name}" },
    { "type": "custom", "format": "\\u001b[32m-----------------------------\\u001b[0m" },
    { "type": "os", "key": "sistema" },
    { "type": "wm", "key": "sessão" },
    { "type": "cpu", "key": "cpu" },
    { "type": "memory", "key": "memoria" },
    { "type": "disk", "key": "disco" },
    { "type": "uptime", "key": "ligado ha" }
  ]
}
"""
    # A card laid out in SECTIONS rather than as one column of keys. This is
    # the look people build by hand and post screenshots of: a tagline, then
    # Vitals / System / Session with a rule over each, then the palette as a
    # row of dots at the bottom.
    #
    # Written with only the module types every fastfetch has -- `custom` for
    # the rules, `break` for the air, `colors` for the dots. No colour escapes
    # inside the format strings: those are version-specific, and a card that
    # prints "{#green}" at somebody is worse than a card that prints grey.
    def sectioned(logo_block, width=46):
        rule = lambda label: ('    { "type": "custom", "format": "── %s %s" },\n'
                              % (label, "─" * max(3, width - len(label) - 4)))
        return (FASTFETCH_HEAD + logo_block + """  "display": {
    "separator": "  ",
    "color": { "keys": "38;2;29;158;117", "title": "38;2;29;158;117" }
  },
  "modules": [
    { "type": "title", "format": "{user-name} @ {host-name}" },
    { "type": "custom", "format": "Genesi OS · um amanhã mais tranquilo" },
    "break",
""" + rule("VITAIS") + """    { "type": "cpu", "key": "CPU" },
    { "type": "gpu", "key": "GPU" },
    { "type": "memory", "key": "MEMORIA" },
    { "type": "disk", "key": "DISCO" },
    "break",
""" + rule("SISTEMA") + """    { "type": "os", "key": "OS" },
    { "type": "kernel", "key": "KERNEL" },
    { "type": "wm", "key": "WM" },
    { "type": "shell", "key": "SHELL" },
    { "type": "packages", "key": "PACOTES" },
    "break",
""" + rule("SESSAO") + """    { "type": "uptime", "key": "LIGADO HA" },
    { "type": "terminal", "key": "TERMINAL" },
    "break",
    { "type": "colors", "symbol": "circle", "paddingLeft": 2 }
  ]
}
""")

    SECTION_PREVIEW = ["matheus @ genesi", "Genesi OS", "── VITAIS ──────",
                       "CPU      Ryzen 7", "MEMORIA  6.2 / 16 GiB",
                       "── SISTEMA ─────", "WM       Hyprland"]

    # An image where the ASCII art goes. `sixel` is the protocol foot speaks --
    # Genesi's default terminal, picked because it needs no OpenGL and so
    # survives a VM -- and it is NOT kitty's, so a config copied from a kitty
    # setup shows nothing here.
    #
    # The picture is downloaded with the card and its path is substituted in,
    # rather than named as a fixed location: pointing at a file that may not
    # be there prints an error where the logo should be.
    shot_asset, _ = wallpaper_asset("dark_forest.png")

    image_big = FASTFETCH_HEAD + """  "logo": {
    "type": "sixel",
    "source": "{{asset:picture}}",
    "width": 34,
    "padding": { "top": 1, "right": 3 }
  },
  "display": { "separator": "  ", "color": { "keys": "green" } },
  "modules": [
    { "type": "title", "format": "{user-name}@{host-name}" },
    "separator",
    { "type": "os", "key": "sistema" },
    { "type": "kernel", "key": "kernel" },
    { "type": "wm", "key": "sessão" },
    { "type": "cpu", "key": "cpu" },
    { "type": "gpu", "key": "gpu" },
    { "type": "memory", "key": "memoria" },
    { "type": "uptime", "key": "ligado ha" }
  ]
}
"""

    image_small = FASTFETCH_HEAD + """  "logo": {
    "type": "sixel",
    "source": "{{asset:picture}}",
    "width": 18,
    "padding": { "top": 1, "right": 2 }
  },
  "display": { "separator": "  " },
  "modules": [
    { "type": "title", "format": "{user-name}" },
    { "type": "os", "format": "{name}" },
    { "type": "wm", "format": "{name}" },
    { "type": "uptime" }
  ]
}
"""

    return [
        item("compact", "Compacto", "Cinco linhas e o logo pequeno.",
             ["curto"], {"text": compact, "logo": "small",
                         "preview": ["matheus@genesi", "sistema  Genesi OS",
                                     "sessao   Hyprland", "memoria  6.2 / 16 GiB"]}),
        item("full", "Completo", "Tudo que dá para contar sobre a máquina.",
             ["longo"], {"text": full, "logo": "full",
                         "preview": ["sistema  Genesi OS x86_64",
                                     "cpu      Ryzen 7 / 16 threads",
                                     "gpu      RTX 3050", "disco    712 / 954 GiB"]}),
        item("bare", "Sem logo", "Só texto, para quem abre muitos terminais.",
             ["minimalista"], {"text": bare, "logo": "none", "keyed": False,
                               "preview": ["  genesi", "  Genesi OS",
                                           "  6.14.2", "  1d 3h"]}),
        item("green", "Verde", "As cores da casa no prompt.",
             ["verde"], {"text": green, "logo": "full",
                         "preview": ["matheus em genesi",
                                     "-----------------------------",
                                     "sistema  Genesi OS", "sessao   Hyprland"]}),
        item("image", "Com imagem", IMAGE_BLURB, ["imagem", "sixel"],
             {"text": image_big, "logo": "image", "asset": shot_asset,
              "preview": ["sistema  Genesi OS", "sessão   Hyprland",
                          "cpu      Ryzen 7", "memoria  6.2 / 16 GiB"]}),
        item("image-small", "Com imagem (pequena)", IMAGE_BLURB,
             ["imagem", "sixel", "curto"],
             {"text": image_small, "logo": "image", "asset": shot_asset,
              "preview": ["genesi", "Genesi OS", "Hyprland", "1d 3h"]}),

        # The sectioned one, with the Genesi leaf.
        item("ficha", "Ficha técnica",
             "Vitais, sistema e sessão separados, com a paleta embaixo. "
             "O jeitão que as pessoas montam à mão.",
             ["seções", "completo"],
             {"text": sectioned(GENESI_LOGO_BLOCK), "logo": "full",
              "preview": SECTION_PREVIEW}),
        item("ficha-limpa", "Ficha técnica (sem logo)",
             "A mesma ficha, sem desenho nenhum na frente.",
             ["seções", "minimalista"],
             {"text": sectioned('  "logo": { "type": "none" },\n'),
              "logo": "none", "preview": SECTION_PREVIEW}),
    ] + [
        # ...and the same ficha with a real picture instead of the leaf. One
        # card per picture, because "an image" is not a look -- WHICH image is
        # the look, and picking one for everybody is how you get a shelf
        # nobody uses.
        item("ficha-" + ident, "Ficha técnica (%s)" % label, IMAGE_BLURB,
             ["seções", "imagem", "sixel"] + tags,
             {"text": sectioned(SIXEL_LOGO_BLOCK), "logo": "image",
              "asset": wallpaper_asset(filename)[0],
              "preview": SECTION_PREVIEW})
        for ident, filename, label, tags in FETCH_PICTURES
    ]


def rices(previous):
    """A whole desktop at once: colours, wallpaper and bar together.

    They used to carry a session lock too, which means applying ANY of these
    started a second locker behind caelestia's own -- the crash on unlock.
    The lock follows the theme and the wallpaper, so a rice still changes it.
    """
    def rice(ident, name, blurb, tags, scheme, wall, bar, colour):
        return {
            "id": "rice-" + ident,
            "section": "rices",
            "name": name,
            "blurb": blurb,
            "author": "Genesi",
            "tags": tags,
            "preview": {"kind": "desktop", "accent": colour,
                        "thumb": "wall-%s.jpg" % wall,
                        "scheme": "theme-" + scheme},
            "includes": ["theme-" + scheme, "wall-" + wall, "bar-" + bar],
            "actions": [],
        }

    made = [
        rice("floresta-viva", "Floresta Viva",
             "Verde fechado e barra rente sobre a mata.",
             ["verde", "natureza"], "everforest-medium-dark", "forest-dark",
             "borda", "#a7c080"),
        rice("orvalho", "Orvalho",
             "Verde claro da casa sobre água parada.",
             ["verde", "calmo"], "caelestia-default-dark", "lake",
             "arejado", "#8fd6ab"),
        rice("noite-baixa", "Noite Baixa",
             "Preto real, barra fina, nada brilhando.",
             ["escuro", "oled"], "darkgreen-hard-dark", "oled-mountains",
             "fio", "#4f8f6a"),
        rice("terra", "Terra",
             "Gruvbox, cidade retrô e barra densa.",
             ["quente", "retro"], "gruvbox-medium-dark", "gruvbox-city",
             "painel", "#d79921"),
        rice("meia-noite", "Meia-Noite",
             "Tokyo Night com neon e barra centralizada.",
             ["escuro", "neon"], "tokyonight-medium-dark", "neocity",
             "centrado", "#7aa2f7"),
        rice("papel", "Papel",
             "Claro, quieto, para trabalhar de dia.",
             ["claro", "minimalista"], "catppuccin-latte-light", "minimal-c",
             "limpo", "#8839ef"),
    ]
    return made


def bundles():
    """Two or three things that go together, and say what they will change."""
    return [
        {
            "id": "bundle-primeira-troca",
            "section": "bundles",
            "name": "Primeira Troca",
            "blurb": "O básico para o desktop deixar de ser o padrão: cor, "
                     "papel de parede e uma barra que respira.",
            "author": "Genesi",
            "tags": ["comeco"],
            "preview": {"kind": "desktop", "accent": "#8fd6ab",
                        "thumb": "wall-nature.jpg"},
            "includes": ["theme-caelestia-default-dark", "wall-nature",
                         "bar-arejado"],
            "actions": [],
        },
        {
            "id": "bundle-terminal",
            "section": "bundles",
            "name": "Vida no Terminal",
            "blurb": "Fastfetch completo e uma barra densa: para quem "
                     "vive no prompt.",
            "author": "Genesi",
            "tags": ["terminal"],
            "preview": {"kind": "desktop", "accent": "#8fd6ab",
                        "thumb": "wall-ink-wave.jpg"},
            "includes": ["fetch-full", "bar-informativo", "wall-ink-wave"],
            "actions": [],
        },
        {
            "id": "bundle-descanso",
            "section": "bundles",
            "name": "Descanso",
            "blurb": "Claro de dia, sem barulho visual: tema claro, papel "
                     "minimalista e barra limpa.",
            "author": "Genesi",
            "tags": ["claro", "calmo"],
            "preview": {"kind": "desktop", "accent": "#40a02b",
                        "thumb": "wall-minimal-c.jpg"},
            "includes": ["theme-everforest-medium-light", "wall-minimal-c",
                         "bar-limpo"],
            "actions": [],
        },
    ]


# ── The OTHER lock: login screens somebody else wrote ──────────────────────
#
# The session lock above is a config file. These are whole Qt applications
# that run as root, before anybody has logged in, and if one of them fails to
# draw the machine has no way in but a text console. So the rules here are
# stricter than anywhere else in this file:
#
#   * Pinned to a COMMIT, never to a branch. "main" is whatever somebody
#     pushed this morning.
#   * Refused unless the theme's own metadata says QtVersion=6 and its QML
#     imports are all Qt6. Half the beautiful SDDM themes on GitHub are Qt5
#     and would be a black screen on Genesi -- that is a build failure here,
#     not a discovery at 3am.
#   * The QML modules each theme imports are read out of its own source and
#     recorded, so the helper installs them BEFORE switching the greeter.
#   * What is recorded is a digest of the CONTENT, not of the tarball. GitHub
#     builds those archives on demand and re-compressed them once already,
#     which changed every checksum in the world without changing one file.
#
# Every one of these is GPL-3.0 or MIT, credited by name and repository in the
# card, and installed unmodified but for the one line that selects a variant.

GREETER_REPOS = {
    # key: (repository, the commit this catalogue was built against)
    "astronaut": ("Keyitdev/sddm-astronaut-theme",
                  "abb3163c724935af888ba5ea9ac0c4f22afd8048"),
    "caelestia": ("ItsABigIgloo/caelestia-sddm",
                  "7843c0f38de1e4f8606976ae0983536bf8ed4c76"),
    "silent": ("uiriansan/SilentSDDM",
               "73380d331fe0f8b8a3b17991bb917a0d438a4d34"),
    "echo": ("xCaptaiN09/echo-sddm",
             "e004121450ff71050d3d76a998b86eafdbb6bf47"),
    "pixie": ("xCaptaiN09/pixie-sddm",
              "1e1a863761f742e8d509d569382b17c112e29fdc"),
    "whereis": ("stepanzubkov/where-is-my-sddm-theme",
                "2fddf85ec80ff02a8e20fdcba51a30b436d76e6c"),
    "hypr": ("ADIOR-enigma/hypr-sddm",
             "52fd4a538fabea2331d9b9f956c2497ff5f9102c"),
}

# key, repo, subpath inside the archive, directory it installs as,
# who wrote it, licence
GREETERS = [
    ("astronaut", "astronaut", "", "genesi-astronaut",
     "keyitdev", "GPL-3.0-or-later"),
    ("caelestia-locklike", "caelestia", "themes/locklike",
     "genesi-caelestia-locklike", "AkhiLeith", "GPL-3.0-or-later"),
    ("caelestia-minimalist", "caelestia", "themes/minimalistV2",
     "genesi-caelestia-minimalist", "Haikalllp", "GPL-3.0-or-later"),
    ("silent", "silent", "", "genesi-silent", "uiriansan", "GPL-3.0-or-later"),
    ("echo", "echo", "", "genesi-echo", "xCaptaiN09", "MIT"),
    ("pixie", "pixie", "", "genesi-pixie", "xCaptaiN09", "MIT"),
    ("whereis", "whereis", "where_is_my_sddm_theme", "genesi-whereis",
     "stepanzubkov", "MIT"),
    # Note what this one is NOT: it does not read the running caelestia shell
    # the way caelestia-sddm does. It is a standalone theme that looks like
    # hyprlock, with its own wallpaper and its own palette in theme.conf. The
    # repository also carries a matugen config for recolouring it from your
    # wallpaper, which needs the install script in sudoers -- so the store
    # does not use it, and the theme works without it.
    ("hypr", "hypr", "", "genesi-hypr", "adior_enigmac", "MIT"),
]

# What a QML import costs in packages. A theme that imports a module the
# machine does not have does not fall back to something plainer -- it fails to
# load, and SDDM shows nothing.
MODULE_PACKAGES = {
    "QtQuick.VirtualKeyboard": "qt6-virtualkeyboard",
    "QtMultimedia": "qt6-multimedia",
    "Qt5Compat.GraphicalEffects": "qt6-5compat",
    "QtQuick.Shapes": "qt6-declarative",
    "QtQuick.Effects": "qt6-declarative",
    "QtQuick.Controls": "qt6-declarative",
    "QtQuick.Layouts": "qt6-declarative",
    "QtQuick.Window": "qt6-declarative",
    "QtQuick": "qt6-declarative",
    "QtQml": "qt6-declarative",
    "SddmComponents": "",          # comes with sddm itself
}

# The biggest screenshot in the catalogue is 2.7 MB. Eight is room to grow
# and still small enough that a card cannot be used to push a file at anybody.
MAX_SHOT_BYTES = 8 * 1024 * 1024

# Imports that only exist in Qt5. Seeing one means the theme was never ported,
# and installing it would be handing somebody a machine they cannot log into.
QT5_ONLY = ("QtGraphicalEffects", "QtQuick.Controls.Styles")

GREETER_ITEMS = [
    # id, greeter key, config file inside the theme (or ""), name, blurb,
    # tags, where the picture comes from
    ("astronaut", "astronaut", "Themes/astronaut.conf", "Astronauta",
     "Um astronauta à deriva, e o campo de senha no meio do espaço.",
     ["espaço", "animado"], "url:astronaut.png"),
    ("astronaut-black-hole", "astronaut", "Themes/black_hole.conf",
     "Buraco Negro", "Fundo animado engolindo a luz. O mais pesado dos dez.",
     ["espaço", "animado", "escuro"], "url:black_hole.png"),
    ("astronaut-cyberpunk", "astronaut", "Themes/cyberpunk.conf", "Cyberpunk",
     "Neon rosa e ciano, chuva na cidade.", ["neon", "animado"],
     "url:cyberpunk.png"),
    ("astronaut-hyprland", "astronaut", "Themes/hyprland_kath.conf",
     "Hyprland", "A garota do Hyprland, animada.", ["anime", "animado"],
     "url:frame_hyprland_kath.png"),
    ("astronaut-jake", "astronaut", "Themes/jake_the_dog.conf", "Jake",
     "Hora de aventura na tela de login.", ["cartoon", "animado"],
     "url:frame_jake_the_dog.png"),
    ("astronaut-japanese", "astronaut", "Themes/japanese_aesthetic.conf",
     "Japonesa", "Torii, montanha e um degradê de fim de tarde.",
     ["paisagem"], "url:japanese_aesthetic.png"),
    ("astronaut-sakura", "astronaut", "Themes/pixel_sakura.conf",
     "Sakura (animada)", "Pétalas caindo em pixel art, em movimento.",
     ["pixel", "animado"], "url:frame_pixel_sakura.png"),
    ("astronaut-sakura-still", "astronaut", "Themes/pixel_sakura_static.conf",
     "Sakura (parada)", "A mesma cena em pixel art, sem animação -- mais leve.",
     ["pixel", "leve"], "url:pixel_sakura_static.png"),
    ("astronaut-hacker", "astronaut",
     "Themes/post-apocalyptic_hacker.conf", "Hacker",
     "Terminal verde sobre ruína. Mono e sujo, do jeito certo.",
     ["terminal", "verde"], "url:post-apocalyptic_hacker.png"),
    ("astronaut-purple-leaves", "astronaut", "Themes/purple_leaves.conf",
     "Folhas Roxas", "Folhagem roxa e um campo discreto embaixo.",
     ["natureza", "roxo"], "url:purple_leaves.png"),

    ("caelestia-locklike", "caelestia-locklike", "", "Caelestia Locklike",
     "A tela de login igual ao bloqueio do caelestia: relógio enorme, "
     "citação, avatar. É o desktop do Genesi antes de entrar nele.",
     ["caelestia", "combina"], "url:caelestia-locklike"),
    ("caelestia-minimalist", "caelestia-minimalist", "",
     "Caelestia Minimalist", "A mesma família, reduzida ao relógio e ao campo.",
     ["caelestia", "minimalista"], "url:caelestia-minimalist"),

    ("silent", "silent", "configs/default.conf", "Silent",
     "Um cartão de vidro no meio da tela. O mais bem acabado da lista.",
     ["vidro", "moderno"], "tar:docs/previews/default.png"),
    ("silent-left", "silent", "configs/default-left.conf", "Silent (esquerda)",
     "O mesmo cartão, encostado à esquerda.", ["vidro", "moderno"],
     "tar:docs/previews/default-left.png"),
    ("silent-right", "silent", "configs/default-right.conf",
     "Silent (direita)", "O mesmo cartão, encostado à direita.",
     ["vidro", "moderno"], "tar:docs/previews/default-right.png"),
    ("silent-mocha", "silent", "configs/catppuccin-mocha.conf",
     "Silent Catppuccin Mocha", "Catppuccin escuro, o de sempre.",
     ["catppuccin", "escuro"], "tar:docs/previews/catppuccin-mocha.png"),
    ("silent-macchiato", "silent", "configs/catppuccin-macchiato.conf",
     "Silent Catppuccin Macchiato", "Catppuccin um tom acima do mocha.",
     ["catppuccin", "escuro"], "tar:docs/previews/catppuccin-macchiato.png"),
    ("silent-frappe", "silent", "configs/catppuccin-frappe.conf",
     "Silent Catppuccin Frappé", "Catppuccin morno.", ["catppuccin"],
     "tar:docs/previews/catppuccin-frappe.png"),
    ("silent-latte", "silent", "configs/catppuccin-latte.conf",
     "Silent Catppuccin Latte", "Catppuccin claro, para quem usa tema claro.",
     ["catppuccin", "claro"], "tar:docs/previews/catppuccin-latte.png"),
    ("silent-everforest", "silent", "configs/everforest.conf",
     "Silent Everforest", "Verde de floresta, que é a cor da casa.",
     ["everforest", "verde"], "tar:docs/previews/everforest.png"),
    ("silent-nord", "silent", "configs/nord.conf", "Silent Nord",
     "Azul frio do Nord.", ["nord", "azul"], "tar:docs/previews/nord.png"),
    ("silent-ken", "silent", "configs/ken.conf", "Silent Ken",
     "Com vídeo de fundo. Bonito, e o mais pesado da prateleira.",
     ["vídeo", "animado"], "tar:docs/previews/ken.png"),
    ("silent-rei", "silent", "configs/rei.conf", "Silent Rei",
     "Também com vídeo de fundo.", ["vídeo", "animado", "anime"],
     "tar:docs/previews/rei.png"),

    ("echo", "echo", "", "Echo",
     "Um terminal do macOS com o log de boot correndo dentro. "
     "Você digita a senha no prompt.", ["terminal", "mono"],
     "tar:assets/screenshots/Screenshot_1.png"),
    ("pixie", "pixie", "", "Pixie",
     "Material You: relógio empilhado, cantos macios, cor de Pixel.",
     ["material", "limpo"], "tar:screenshots/login_screen.png"),

    ("whereis", "whereis", "theme.conf", "Cadê meu tema?",
     "Fundo preto e a senha em letras gigantes. Nada mais na tela.",
     ["minimalista", "rápido"], "tar:screenshots/classic.png"),
    ("whereis-blue", "whereis", "example_configs/blue.conf",
     "Cadê meu tema? (azul)", "O mesmo nada, em azul.",
     ["minimalista", "azul"], "tar:screenshots/blue.png"),
    ("whereis-grey", "whereis", "example_configs/grey.conf",
     "Cadê meu tema? (cinza)", "O mesmo nada, em cinza.",
     ["minimalista"], "tar:screenshots/grey.png"),
    ("whereis-nord", "whereis", "example_configs/nord.conf",
     "Cadê meu tema? (nord)", "O mesmo nada, com a paleta Nord.",
     ["minimalista", "nord"], "tar:screenshots/nord.png"),
    ("whereis-rose", "whereis", "example_configs/rose-pine-moon.conf",
     "Cadê meu tema? (rosé pine)", "O mesmo nada, em rosé pine moon.",
     ["minimalista", "rosa"], "tar:screenshots/rose-pine-moon.png"),
    ("whereis-tree", "whereis", "example_configs/tree.conf",
     "Cadê meu tema? (árvore)", "Com uma foto atrás, para provar que dá.",
     ["minimalista", "foto"], "tar:screenshots/tree.png"),
    ("hypr", "hypr", "", "Hypr",
     "O jeitão do hyprlock na tela de login: relógio empilhado, cartão "
     "no meio, paleta fixa. Não segue o seu papel de parede.",
     ["minimalista", "escuro"], "tar:screenshot.png"),
]

# The pictures that are not in the repository itself. The astronaut previews
# live in the author's screenshots repository; the two caelestia ones are the
# images from its README.
GREETER_PICTURES = {
    "caelestia-locklike":
        "https://github.com/user-attachments/assets/"
        "ef2c973d-c723-4a71-b535-04951a2c3130",
    "caelestia-minimalist":
        "https://github.com/user-attachments/assets/"
        "02207bd5-fa7b-4312-9ff2-583f57fc5f18",
}
# Pinned to a commit for the same reason the themes are: this URL is now in
# the catalogue and fetched on the user's machine, so a branch here would mean
# the picture on the card can change under us without the catalogue moving.
# (The second "master" is a directory in that repository, not a ref.)
ASTRONAUT_SHOTS = ("https://raw.githubusercontent.com/Keyitdev/screenshots/"
                   "ebe29f1f9efbb055687cb918a284d7aee62921e3"
                   "/sddm-astronaut-theme/master/")

# Which greeter comes out of which archive: three of them share two downloads.
REPO_OF = {key: repo for key, repo, _, _, _, _ in GREETERS}

_ARCHIVES = {}


def greeter_archive(repo_key):
    """The tarball, downloaded once however many themes come out of it."""
    if repo_key not in _ARCHIVES:
        repo, ref = GREETER_REPOS[repo_key]
        url = "https://codeload.github.com/%s/tar.gz/%s" % (repo, ref)
        print("  fetching %s" % url)
        data = get(url, binary=True)
        if not data.startswith(b"\x1f\x8b"):
            raise SystemExit("%s did not answer with a gzip archive" % url)
        _ARCHIVES[repo_key] = (url, data)
    return _ARCHIVES[repo_key]


def archive_root(repo_key):
    repo, ref = GREETER_REPOS[repo_key]
    return "%s-%s" % (repo.split("/")[1], ref)


def greeter_members(repo_key):
    import tarfile
    _, data = greeter_archive(repo_key)
    return tarfile.open(fileobj=io.BytesIO(data), mode="r:gz")


def tree_digest_of(repo_key, subpath):
    """The same digest genesi-store-helper computes after it unpacks.

    Every regular file under the subtree, by relative path in sorted order,
    path then bytes. Not the archive's checksum: see the note at the top of
    this section, and ci/store-test.py, which runs this function and the
    helper's over the same tree and fails if they ever disagree.
    """
    prefix = "/".join(x for x in (archive_root(repo_key), subpath) if x)
    files = {}
    with greeter_members(repo_key) as tar:
        for member in tar:
            if not member.isfile():
                continue
            name = member.name
            if name != prefix and not name.startswith(prefix + "/"):
                continue
            rel = name[len(prefix):].lstrip("/")
            files[rel] = tar.extractfile(member).read()
    if not files:
        raise SystemExit("nothing under %s in the %s archive"
                         % (prefix, repo_key))
    digest = hashlib.sha256()
    for rel in sorted(files):
        digest.update(rel.encode("utf-8"))
        digest.update(b"\0")
        digest.update(files[rel])
        digest.update(b"\0")
    return digest.hexdigest(), files


def greeter_needs(files):
    """What this theme's own QML says it cannot run without."""
    needs = set()
    for rel, blob in files.items():
        if not rel.endswith(".qml"):
            continue
        text = blob.decode("utf-8", "replace")
        for line in text.splitlines():
            line = line.strip()
            if not line.startswith("import "):
                continue
            module = line.split()[1]
            for bad in QT5_ONLY:
                if module == bad or module.startswith(bad + "."):
                    raise SystemExit(
                        "%s imports %s, which is Qt5 only -- on Genesi that "
                        "theme is a black screen at boot" % (rel, module))
            for known, package in MODULE_PACKAGES.items():
                if module == known or module.startswith(known + "."):
                    if package:
                        needs.add(package)
                    break
    if any(rel.endswith(".svg") for rel in files):
        needs.add("qt6-svg")
    return sorted(needs)


def greeter_confs(files):
    return sorted(rel for rel in files if rel.endswith(".conf"))


def greeter_picture(item_id, key, where):
    """Where the screenshot IS, verified now and fetched on the machine.

    These pictures are not ours. They are the authors' screenshots, and some
    of what is in them is not even theirs -- the astronaut wallpapers are
    described by their own README as "copied from one user to another", and
    two of them are frames of a cartoon and of a commercial game. Shipping
    them inside a Genesi package would be Genesi redistributing that. Naming
    them is not: the picture comes from the same place the theme does, pinned
    to the same kind of commit, checked against the same kind of digest.

    So this downloads the file ONCE, at build time, to prove the link works
    and to record what the bytes are -- and then throws the bytes away.

    A `tar:` path is relative to the root of the downloaded archive, which is
    also its path in the repository, so it can be named directly rather than
    making somebody fetch twenty megabytes of theme to see one screenshot.
    """
    kind, _, rest = where.partition(":")
    if kind == "url":
        url = GREETER_PICTURES.get(rest) or (ASTRONAUT_SHOTS + rest)
    else:
        repo, ref = GREETER_REPOS[REPO_OF[key]]
        url = "https://raw.githubusercontent.com/%s/%s/%s" % (repo, ref, rest)
    data = get(url, binary=True)
    for mime, head in (("image/png", b"\x89PNG"), ("image/jpeg", b"\xff\xd8\xff")):
        if data.startswith(head):
            break
    else:
        raise SystemExit("%s is not a picture -- the link is broken" % url)
    if len(data) > MAX_SHOT_BYTES:
        raise SystemExit("%s is %.1f MB; a screenshot stops at %d MB"
                         % (url, len(data) / 1048576.0,
                            MAX_SHOT_BYTES // (1 << 20)))
    return {"url": url, "type": mime, "bytes": len(data),
            "sha256": hashlib.sha256(data).hexdigest()}


# Repositories that hold a COLLECTION rather than a theme. qylock is 604 MB
# of tarball; the Minecraft login screen inside it is 200 KB. Downloading the
# first to install the second is not a thing to do to somebody's connection,
# so a theme out of one of these is described FILE BY FILE: its own files,
# pinned to the same commit, each with its own sha256.
# The qylock themes, each its own card. Skipped: clockwork, which does not
# declare QtVersion=6 -- on Genesi that is a black screen at boot, and the
# build refuses it for the same reason it refuses a Qt5 import.
#
# id, directory in the repo, name, blurb, tags
QYLOCK_THEMES = [
    ("minecraft", "minecraft", "Minecraft",
     "A tela de título, com a fonte e tudo.", ["jogo", "pixel"]),
    ("terraria", "terraria", "Terraria",
     "Madeira, tochas e o menu do jogo.", ["jogo", "pixel"]),
    ("nier", "nier-automata", "NieR: Automata",
     "Areia, serifa e o silêncio do jogo.", ["jogo", "minimalista"]),
    ("windows7", "windows_7", "Windows 7",
     "Aquele azul. Sim, aquele mesmo.", ["retro", "nostalgia"]),
    # Skipped: "nothing", which is QML and two fonts with no picture in it
    # at all. There is nothing to put on its card, and a blank card among
    # thirty-five photographs is what this shelf keeps being rebuilt to stop.
    ("ninja-gaiden", "ninja_gaiden", "Ninja Gaiden",
     "Oito bits e um ninja.", ["jogo", "retro", "pixel"]),
    ("field", "field", "Campo",
     "Um campo aberto e a luz baixa.", ["natureza", "calmo"]),
    ("ninesols", "ninesols", "Nine Sols",
     "Traço oriental em vermelho e osso.", ["jogo", "arte"]),
    ("girl-coffee", "girl-coffee", "Café",
     "Alguém tomando café, desenhado.", ["arte", "calmo"]),
    ("girl-pillow", "girl-pillow", "Travesseiro",
     "O sono que você não teve.", ["arte", "calmo"]),
    ("pixel-coffee", "pixel-coffee", "Café (pixel)",
     "O mesmo café, em pixel art animada.", ["pixel", "animado"]),
    ("pixel-dusk", "pixel-dusk-city", "Cidade ao Anoitecer",
     "Telhados e a última luz, em pixel.", ["pixel", "cidade", "animado"]),
    ("pixel-waterfall", "pixel-waterfall", "Cachoeira",
     "Água caindo, quadro a quadro.", ["pixel", "natureza", "animado"]),
    ("pixel-munchlax", "pixel-munchlax", "Munchlax",
     "Um pokémon dormindo na sua tela de login.", ["pixel", "jogo"]),
    ("women-umbrella", "women-umbrella", "Guarda-chuva",
     "Chuva, um guarda-chuva e neon.", ["arte", "cidade"]),
    ("material-you", "material-you", "Material You",
     "O desenho do Android, claro.", ["material", "claro"]),
    ("material-you-dark", "material-you-dark", "Material You (escuro)",
     "O mesmo, no escuro.", ["material", "escuro"]),
    ("man-bicycle", "man-bicycle", "Bicicleta",
     "Uma estrada, uma bicicleta, fim de tarde.", ["arte", "calmo"]),
    ("r1999", "R1999_2", "Reverse: 1999",
     "Art déco e um relógio parado.", ["jogo", "arte"]),
    ("pixel-night-city", "pixel-night-city", "Cidade Noturna",
     "Neon em pixel, com chuva.", ["pixel", "cidade", "animado"]),
    ("pixel-sakura", "pixel-sakura", "Sakura (pixel)",
     "Pétalas caindo, quadro a quadro.", ["pixel", "natureza", "animado"]),
    ("pixel-rainyroom", "pixel-rainyroom", "Quarto na Chuva",
     "A janela, a chuva, a luminária.", ["pixel", "calmo", "animado"]),
    ("star-rail", "star-rail", "Star Rail",
     "O trem entre as estrelas.", ["jogo", "espaço"]),
    ("dog-samurai", "dog-samurai", "Cão Samurai",
     "Exatamente o que está escrito.", ["arte", "jogo"]),
    ("pixel-emerald", "pixel-emerald", "Esmeralda",
     "Verde em pixel, do jeito da casa.", ["pixel", "verde"]),
    ("winter", "winter", "Inverno",
     "Neve caindo devagar.", ["natureza", "frio", "animado"]),
    ("enfield", "enfield", "Enfield",
     "Uma moto antiga e poeira.", ["arte", "retro"]),
    ("pixel-cyberpunk", "pixel-cyberpunk", "Cyberpunk (pixel)",
     "Neon, fumaça e oito bits.", ["pixel", "cidade", "animado"]),
    ("wuwa", "wuwa", "Wuthering Waves",
     "Vento, capa e horizonte.", ["jogo", "arte"]),
    ("pixel-skyscrapers", "pixel-skyscrapers", "Arranha-céus",
     "A cidade de cima, em pixel.", ["pixel", "cidade"]),
    ("sword", "sword", "Espada",
     "Uma lâmina e muito preto.", ["arte", "escuro"]),
    ("pixel-hollowknight", "pixel-hollowknight", "Hollow Knight",
     "Hallownest, em pixel e azul.", ["jogo", "pixel", "escuro"]),
    ("osu", "osu", "osu!",
     "Cinco fundos e o rosa de sempre. O maior da prateleira.",
     ["jogo", "rosa"]),
    ("forest", "forest", "Floresta (qylock)",
     "Mata fechada, em altíssima resolução.", ["natureza", "verde"]),
    ("genshin", "Genshin", "Genshin Impact",
     "Teyvat na tela de login.", ["jogo", "arte"]),
    ("last-of-us", "last-of-us", "The Last of Us",
     "O mundo depois. O mais pesado de todos.", ["jogo", "escuro"]),
]

FILE_REPOS = {
    "qylock": ("Darkkal44/qylock",
               "f6561e2ceae33f26e5e660742a5df2f725cbe514"),
}

# The biggest theme in qylock is 75 MB (osu, which is five full-resolution
# backgrounds); most are under one megabyte.
MAX_THEME_BYTES = 96 * 1024 * 1024

_TREES = {}


# A preview picture the card can actually fill itself with.
MIN_SHOT_WIDTH = 1280

# Files that are a MARK, not a picture of the screen. qylock's Genshin theme
# ships a 2000x2000 logo, which is the highest-resolution image in it and the
# worst possible preview: a card showing a logo tells you nothing about the
# login screen it installs.
LOGO_NAMES = ("logo", "title", "avatar", "pfp", "mark")


def theme_still(spec):
    """The sharpest picture of the theme ITSELF, or None.

    Backgrounds only. The largest file is often a logo or an avatar, and
    "biggest image" would have put a 2000x2000 Genshin wordmark on a card
    whose job is to show what the screen looks like.
    """
    best = None
    for entry in spec["files"]:
        path = entry["path"].lower()
        if not path.endswith((".png", ".jpg", ".jpeg")):
            continue
        stem = os.path.splitext(os.path.basename(path))[0]
        if any(word in stem for word in LOGO_NAMES):
            continue
        if best is None or entry["bytes"] > best["bytes"]:
            best = entry
    if not best:
        return None
    raw = get(spec["base"] + "/" + urllib.parse.quote(best["path"]), binary=True)
    width, _height = wallpaper_size(raw)
    kind = "image/png" if best["path"].lower().endswith(".png") else "image/jpeg"
    return {"url": spec["base"] + "/" + urllib.parse.quote(best["path"]),
            "type": kind, "bytes": best["bytes"], "sha256": best["sha256"],
            "width": width}


def theme_motion(key, subdir):
    """The author's animated preview of the theme, or None.

    qylock ships one per theme in Assets/, which matters because nineteen of
    these have an MP4 for a background and no still image at all. They are
    400x225 every one of them, though -- fine as the thing that MOVES when
    you point at a card, far too small to BE the card.
    """
    repo, ref = FILE_REPOS["qylock"]
    flat = lambda name: re.sub(r"[^a-z0-9]", "", name.lower())
    assets = {flat(os.path.splitext(os.path.basename(p))[0]): p
              for p in repo_tree(repo, ref)
              if p.startswith("Assets/") and p.lower().endswith((".gif", ".png"))}
    want = flat(subdir)
    aliases = {"windows7": "win7", "lastofus": "thelastofus"}
    path = (assets.get(want) or assets.get(want.replace("the", "", 1))
            or assets.get(flat(aliases.get(want, ""))))
    if not path:
        return None
    url = ("https://raw.githubusercontent.com/%s/%s/%s"
           % (repo, ref, urllib.parse.quote(path)))
    raw = get(url, binary=True)
    width, _height = wallpaper_size(raw)
    return {"url": url,
            "type": "image/gif" if path.lower().endswith(".gif") else "image/png",
            "bytes": len(raw), "sha256": hashlib.sha256(raw).hexdigest(),
            "width": width}


def theme_backdrop(key, spec, subdir):
    """What a collection theme shows on its card: a still, and maybe motion.

    The still is the theme's own background where it has one big enough --
    two and a half thousand pixels wide in places, against the 400x225 the
    author's GIF is. The GIF is kept as the thing that plays when you point
    at the card, so the sharp picture is what you see and the motion is there
    when you want it.

    Eighteen of these are video-backgrounded and have no still at all. For
    those the GIF IS the card, and the drawing fills the rest of it with a
    blurred copy rather than stretching 400 pixels across a window.
    """
    still = theme_still(spec)
    motion = theme_motion(key, subdir)
    if not still and not motion:
        raise SystemExit("%s has no preview anywhere in the collection" % key)
    # A sharp still wins. Below that the author's animation is the better
    # picture, because it is at least of the whole screen. A small still is
    # still better than nothing -- MIN_SHOT_WIDTH is a preference, not a bar
    # to clear, and one theme (ninesols) has only a 1080px background and no
    # animation at all.
    if still and still["width"] >= MIN_SHOT_WIDTH:
        shot = still
    elif motion:
        shot = motion
    else:
        shot = still
    out = dict(shot)
    if motion and motion is not shot:
        out["motion"] = motion
    return out


def repo_tree(repo, ref):
    """Every file in a repository at one commit. One API call, not 604 MB."""
    key = (repo, ref)
    if key not in _TREES:
        data = json.loads(get("https://api.github.com/repos/%s/git/trees/%s"
                              "?recursive=1" % (repo, ref)))
        if data.get("truncated"):
            raise SystemExit("the file list for %s is truncated, so this build "
                             "cannot describe it completely" % repo)
        _TREES[key] = sorted(b["path"] for b in data.get("tree", [])
                             if b.get("type") == "blob")
    return _TREES[key]


def theme_files(repo_key, subdir):
    """One theme out of a collection: its files, their digests, and the bytes.

    Everything is fetched here, at build time, to prove the links work and to
    record what the bytes are. The bytes are returned so the rest of the build
    can read the theme's QML imports and its config list out of them, exactly
    as it does for a theme that arrived in a tarball -- and then they are
    thrown away. What ships is paths and digests.
    """
    repo, ref = FILE_REPOS[repo_key]
    prefix = subdir.rstrip("/") + "/"
    paths = [p for p in repo_tree(repo, ref) if p.startswith(prefix)]
    if not paths:
        raise SystemExit("%s has no %s at %s" % (repo, subdir, ref[:8]))

    files, fetched, total = [], {}, 0
    for path in paths:
        rel = path[len(prefix):]
        # A .gitkeep holding an empty font directory is not part of the theme.
        if not rel or os.path.basename(rel) == ".gitkeep":
            continue
        raw = get("https://raw.githubusercontent.com/%s/%s/%s"
                  % (repo, ref, urllib.parse.quote(path)), binary=True)
        total += len(raw)
        if total > MAX_THEME_BYTES:
            raise SystemExit("%s/%s is over %d MB"
                             % (repo, subdir, MAX_THEME_BYTES // (1 << 20)))
        files.append({"path": rel, "bytes": len(raw),
                      "sha256": hashlib.sha256(raw).hexdigest()})
        fetched[rel] = raw
    if not files:
        raise SystemExit("%s/%s has no files worth installing" % (repo, subdir))

    # The same digest the helper will compute once it has written them: path,
    # then bytes, sorted by path. ci/store-test.py runs the helper's own
    # function over a real directory and compares the two.
    digest = hashlib.sha256()
    for entry in sorted(files, key=lambda f: f["path"]):
        digest.update(entry["path"].encode("utf-8"))
        digest.update(b"\0")
        digest.update(fetched[entry["path"]])
        digest.update(b"\0")
    return files, digest.hexdigest(), fetched


def greeters():
    """The greeters map and the cards that point into it."""
    specs = {}
    trees = {}
    for key, repo_key, subpath, install_as, author, licence in GREETERS:
        digest, files = tree_digest_of(repo_key, subpath)
        trees[key] = files
        repo, ref = GREETER_REPOS[repo_key]
        url, data = greeter_archive(repo_key)
        meta = files.get("metadata.desktop", b"").decode("utf-8", "replace")
        if "QtVersion=6" not in meta.replace(" ", ""):
            raise SystemExit("%s does not say QtVersion=6, so it is a Qt5 "
                             "theme and would not come up" % key)
        specs[key] = {
            "name": repo.split("/")[1],
            "source": "https://github.com/%s/tree/%s" % (repo, ref),
            "author": author,
            "license": licence,
            "url": url,
            "sha256": hashlib.sha256(data).hexdigest(),
            "bytes": len(data),
            "subpath": "/".join(x for x in (archive_root(repo_key), subpath) if x),
            "tree": digest,
            "install_as": install_as,
            "needs": greeter_needs(files),
            "confs": greeter_confs(files),
        }

    # The collection themes: same map, same checks, described file by file.
    for ident, subdir, name, blurb, tags in QYLOCK_THEMES:
        key = "qylock-" + ident
        files, digest, fetched = theme_files("qylock", "themes/" + subdir)
        meta = fetched.get("metadata.desktop", b"").decode("utf-8", "replace")
        if "QtVersion=6" not in meta.replace(" ", ""):
            raise SystemExit("%s does not say QtVersion=6, so it is a Qt5 "
                             "theme and would not come up" % key)
        repo, ref = FILE_REPOS["qylock"]
        specs[key] = {
            "name": subdir,
            "source": "https://github.com/%s/tree/%s/themes/%s"
                      % (repo, ref, subdir),
            "author": "Darkkal44",
            "license": "GPL-3.0-or-later",
            # No `url`: there is no archive. `base` is what each file hangs
            # off, and every one of them carries its own digest.
            "base": "https://raw.githubusercontent.com/%s/%s/themes/%s"
                    % (repo, ref, urllib.parse.quote(subdir)),
            "files": files,
            "bytes": sum(f["bytes"] for f in files),
            "tree": digest,
            "install_as": "genesi-" + key,
            "needs": greeter_needs(fetched),
            "confs": greeter_confs(fetched),
        }
        trees[key] = fetched

    out = []
    for ident, subdir, name, blurb, tags in QYLOCK_THEMES:
        key = "qylock-" + ident
        spec = specs[key]
        out.append({
            "id": "login-" + key,
            "section": "login",
            "name": name,
            "blurb": blurb,
            "family": "login",
            "author": spec["author"],
            "license": spec["license"],
            "source": spec["source"],
            "tags": ["login", "antes da sessão", "qylock"] + tags,
            "needs_root": True,
            "download": spec["bytes"],
            # The card's picture is the theme's OWN background: already
            # fetched, already hashed, and the most honest preview there is,
            # because it is literally what you will be looking at.
            "preview": {"kind": "login", "theme": key,
                        "shot": theme_backdrop(key, spec, subdir)},
            "actions": [{"action": "greeter", "key": key}],
        })

    for (ident, key, conf, name, blurb, tags, picture) in GREETER_ITEMS:
        spec = specs[key]
        if conf and conf not in spec["confs"]:
            raise SystemExit("%s asks for %s, which %s does not have"
                             % (ident, conf, key))
        action = {"action": "greeter", "key": key}
        if conf:
            action["conf"] = conf
        out.append({
            "id": "login-" + ident,
            "section": "login",
            "name": name,
            "blurb": blurb,
            "family": "login",
            "author": spec["author"],
            "license": spec["license"],
            "source": spec["source"],
            "tags": ["login", "antes da sessão"] + tags,
            "needs_root": True,
            "download": spec["bytes"],
            "preview": {"kind": "login", "theme": key,
                        "shot": greeter_picture(ident, key, picture)},
            "actions": [action],
        })
    return specs, out


if __name__ == "__main__":
    build()
