#!/usr/bin/env python3
"""
build-catalog.py — writes catalog/catalog.json, and is the reason it can be
trusted.

The catalogue is DATA: every item is a name, a picture and a list of actions
out of the vocabulary genesi-store implements. Nothing in it is code. But the
picture comes from somewhere, and "somewhere" is the part that rots -- links
die, files are replaced, repositories are renamed. So the catalogue is not
hand-written: it is generated by this script, which

  * fetches every wallpaper it lists and records the SIZE and the SHA-256 it
    got, so the store can refuse a file that changed under it;
  * reads caelestia's own scheme files to get the colours each theme card is
    painted in, rather than a person retyping thirty palettes;
  * fails loudly on a link that does not answer, so a dead item is a build
    failure here instead of a broken card on somebody's desktop.

Re-run it when adding items, or to refresh what the links serve:

    python3 build-catalog.py            # verify and write
    python3 build-catalog.py --offline  # rebuild the text-only items

Sources, and why these: the wallpapers come from one MIT-licensed collection
(D3Ext/aesthetic-wallpapers), so there is a single licence to honour and a
single repository to check rather than twenty. The colour schemes come from
caelestia-cli, which is already installed -- applying one downloads nothing at
all. The bar arrangements are Genesi's own presets, already shipped.
"""
import hashlib
import io
import json
import os
import sys
import time
import urllib.request

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "catalog", "catalog.json")
OFFLINE = "--offline" in sys.argv

WALL_REPO = "https://raw.githubusercontent.com/D3Ext/aesthetic-wallpapers/main/images/"
SCHEME_REPO = ("https://raw.githubusercontent.com/caelestia-dots/cli/main/"
               "src/caelestia/data/schemes/")

SECTIONS = [
    {"id": "discover", "label": "Descobrir", "label_en": "Discover",
     "icon": "home", "blurb": "O que vale a pena hoje."},
    {"id": "rices", "label": "Ambientes", "label_en": "Rices", "icon": "grid",
     "blurb": "Um desktop inteiro, de uma vez."},
    {"id": "themes", "label": "Temas", "label_en": "Themes", "icon": "palette",
     "blurb": "A cor de tudo, do topo ao terminal."},
    # These were one shelf, and the blurb on it said "the session one and the
    # login one, which are two" -- a label apologising for the shelf it was
    # on. They are two different programs, at two different moments, and only
    # one of them can lock you out of the machine.
    {"id": "login", "label": "Tela de login", "label_en": "Login screens",
     "icon": "login", "blurb": "Antes de entrar: o que pede sua senha no boot."},
    {"id": "lockscreens", "label": "Bloqueio da sessão", "label_en": "Lockscreens",
     "icon": "lock", "blurb": "Já dentro: quando você tranca e volta."},
    {"id": "bars", "label": "Barras", "label_en": "Bar styles", "icon": "bar",
     "blurb": "Quinze arranjos da barra."},
    {"id": "fastfetch", "label": "Fastfetch", "label_en": "Fastfetch",
     "icon": "terminal", "blurb": "O cartão de visita do terminal."},
    {"id": "decor", "label": "Decoração", "label_en": "Decor", "icon": "image",
     "blurb": "Papéis de parede e detalhes."},
    {"id": "bundles", "label": "Coleções", "label_en": "Bundles", "icon": "box",
     "blurb": "Combinações que já vêm casadas."},
    {"id": "plugins", "label": "Plugins", "label_en": "Plugins", "icon": "plug",
     "blurb": "Em breve."},
]

# ── Wallpapers ──────────────────────────────────────────────────────────────
# Chosen to lead with Genesi's own weather -- forest, water, green light --
# and then widen. The name is what a person reads; the file is what the link
# serves.
WALLS = [
    ("forest-dark", "dark_forest.png", "Floresta Escura",
     "Mata fechada ao anoitecer.", ["natureza", "escuro", "verde"]),
    ("nature", "nature.jpg", "Natureza",
     "Verde aberto, sem pressa.", ["natureza", "verde"]),
    ("everforest-robin", "everforest_robin.png", "Everforest",
     "A paleta everforest em desenho.", ["natureza", "verde", "arte"]),
    ("lake", "lake.jpg", "Lago",
     "Água parada e montanha.", ["natureza", "agua", "calmo"]),
    ("art-lake", "art-lake.png", "Lago Ilustrado",
     "O mesmo silêncio, desenhado.", ["arte", "agua", "calmo"]),
    ("mountains", "mountains.png", "Montanhas",
     "Camadas até o horizonte.", ["natureza", "minimalista"]),
    ("golden-mountains", "golden-mountains.png", "Montanhas Douradas",
     "Fim de tarde nos picos.", ["natureza", "quente"]),
    ("oled-mountains", "oled-mountains.jpg", "Montanhas OLED",
     "Preto real, para telas OLED.", ["escuro", "oled", "minimalista"]),
    ("moon", "moon.png", "Lua",
     "Uma lua e nada mais.", ["escuro", "minimalista", "noite"]),
    ("falltree", "falltree.jpg", "Outono",
     "Uma árvore em queda de folhas.", ["natureza", "quente"]),
    ("green-sun", "green-sun.jpg", "Sol Verde",
     "Luz filtrada por folhas.", ["verde", "natureza"]),
    ("tree-castle", "tree-nature-castleinsky.png", "Castelo no Céu",
     "Árvore, castelo, nuvem.", ["arte", "natureza"]),
    ("ink-wave", "ink_wave.png", "Onda de Tinta",
     "Nanquim em movimento.", ["arte", "escuro", "minimalista"]),
    ("blue-waves", "blue-waves.png", "Ondas Azuis",
     "Curvas frias e limpas.", ["minimalista", "frio"]),
    ("minimal-c", "minimal_c.png", "Minimal",
     "Quase nada, bem colocado.", ["minimalista", "escuro"]),
    ("arch-nord", "arch-nord-dark.png", "Arch Nord",
     "O logo, em nord.", ["escuro", "frio", "arch"]),
    ("gruvbox-city", "gruvbox_retrocity.png", "Cidade Gruvbox",
     "Retro em terra e mostarda.", ["quente", "retro", "cidade"]),
    ("neocity", "neocity.png", "Neocidade",
     "Neon e chuva.", ["cidade", "escuro", "neon"]),
]

# ── Colour schemes ─────────────────────────────────────────────────────────
# (family, flavour, mode, name, blurb). Everything here ships with
# caelestia-cli, so applying one is instant and offline.
SCHEMES = [
    ("caelestia", "default", "dark", "Caelestia", "O tom da casa, no escuro."),
    ("caelestia", "default", "light", "Caelestia Claro", "O mesmo, na luz."),
    ("darkgreen", "hard", "dark", "Verde Profundo", "Quase preto, com seiva."),
    ("darkgreen", "medium", "dark", "Verde Mata", "Verde sem gritar."),
    ("everforest", "medium", "dark", "Everforest", "Musgo, pedra e madeira."),
    ("everforest", "hard", "dark", "Everforest Duro", "O mesmo, com mais contraste."),
    ("everforest", "medium", "light", "Everforest Claro", "Papel e folha."),
    ("everblush", "medium", "dark", "Everblush", "Escuro com um rubor."),
    ("catppuccin", "mocha", "dark", "Catppuccin Mocha", "O pastel que todo mundo conhece."),
    ("catppuccin", "macchiato", "dark", "Catppuccin Macchiato", "Um passo mais claro."),
    ("catppuccin", "frappe", "dark", "Catppuccin Frappe", "Meio do caminho."),
    ("catppuccin", "latte", "light", "Catppuccin Latte", "Claro, sem estourar."),
    ("gruvbox", "medium", "dark", "Gruvbox", "Terra, mostarda e ferrugem."),
    ("gruvbox", "hard", "dark", "Gruvbox Duro", "Fundo mais fechado."),
    ("gruvbox", "soft", "dark", "Gruvbox Macio", "Fundo mais aberto."),
    ("gruvbox", "medium", "light", "Gruvbox Claro", "O mesmo, de dia."),
    ("nord", "medium", "dark", "Nord", "Gelo e aço."),
    ("tokyonight", "medium", "dark", "Tokyo Night", "Cidade às três da manhã."),
    ("rosepine", "main", "dark", "Rose Pine", "Vinho e pinho."),
    ("rosepine", "moon", "dark", "Rose Pine Moon", "Um pouco mais alto."),
    ("rosepine", "dawn", "light", "Rose Pine Dawn", "O amanhecer da mesma."),
    ("dracula", "medium", "dark", "Dracula", "Roxo clássico."),
    ("onedark", "default", "dark", "One Dark", "O tema de editor virou desktop."),
    ("oldworld", "default", "dark", "Old World", "Sepia e quieto."),
    ("solarized", "medium", "dark", "Solarized", "O mais estudado de todos."),
    ("shadotheme", "default", "dark", "Shado", "Cinza com um fio de cor."),
]

# ── Bar arrangements ───────────────────────────────────────────────────────
# Genesi's own presets, already installed by genesi-caelestia-settings.
BARS = [
    ("10-padrao", "Padrão", "A barra como o caelestia entrega."),
    ("15-borda", "Rente", "Sem moldura: encostada na borda da tela."),
    ("20-centrado", "Centralizado", "Logo em cima, espaços no meio, o resto embaixo."),
    ("25-fio", "Fio", "O mais estreito que dá para acertar com o mouse."),
    ("30-ilha", "Ilha", "Cantos bem redondos, barra na beirada."),
    ("40-numeros", "Numeros", "Espaços de trabalho numerados."),
    ("45-arejado", "Arejado", "Mais espaço entre tudo."),
    ("50-janelas", "Janelas", "Mostra as janelas abertas."),
    ("55-painel", "Painel", "Denso, como um painel de controle."),
    ("60-informativo", "Informativo", "Tudo que dá para medir, medido."),
    ("70-compacto", "Compacto", "O essencial, junto."),
    ("80-limpo", "Limpo", "So o necessario."),
    ("85-relogio", "Relogio", "O relógio em primeiro lugar."),
    ("90-trilha", "Trilha", "Uma linha contínua."),
    ("95-oculta", "Oculta", "Some até você precisar."),
]


def get(url, binary=False):
    request = urllib.request.Request(url, headers={"User-Agent": "genesi-store-build"})
    with urllib.request.urlopen(request, timeout=45) as response:
        data = response.read()
    return data if binary else data.decode("utf-8")


def scheme_colours(family, flavour, mode):
    """The five colours a theme card is painted in, from caelestia's own file."""
    url = "%s%s/%s/%s.txt" % (SCHEME_REPO, family, flavour, mode)
    want = ("background", "onBackground", "primary", "secondary", "tertiary",
            "surface")
    found = {}
    for line in get(url).splitlines():
        parts = line.split()
        if len(parts) == 2 and parts[0] in want:
            found[parts[0]] = "#" + parts[1].lower()
    missing = [k for k in want if k not in found]
    if missing:
        raise SystemExit("scheme %s/%s/%s has no %s"
                         % (family, flavour, mode, ", ".join(missing)))
    return found


def thumbnail(ident, data, filename):
    """A small picture of the wallpaper, shipped IN the package.

    Without this a decor card is a grey rectangle with a file size in it until
    somebody downloads the wallpaper -- which is backwards, because the picture
    is the reason to download it. 480px of JPEG is about 25 kB, so eighteen of
    them cost less than half a megabyte and the shelf becomes a shelf of
    pictures. They are also what the lock screens, the rices and the
    collections are drawn over, so one download feeds four shelves.
    """
    from PySide6.QtGui import QGuiApplication, QImage
    from PySide6.QtCore import Qt
    global _APP
    try:
        _APP
    except NameError:
        _APP = QGuiApplication([])
    image = QImage.fromData(data)
    if image.isNull():
        raise SystemExit("could not read %s as an image" % filename)
    small = image.scaledToWidth(480, Qt.SmoothTransformation)
    out = os.path.join(HERE, "catalog", "thumbs")
    os.makedirs(out, exist_ok=True)
    name = ident + ".jpg"
    if not small.save(os.path.join(out, name), "JPG", 72):
        raise SystemExit("could not write the thumbnail for " + ident)
    return name


def wallpaper_asset(filename):
    url = WALL_REPO + filename
    data = get(url, binary=True)
    kind = "image/png" if filename.endswith(".png") else "image/jpeg"
    head = {"image/png": b"\x89PNG", "image/jpeg": b"\xff\xd8\xff"}[kind]
    if not data.startswith(head):
        raise SystemExit("%s is not %s -- the link is broken" % (url, kind))
    # The bytes come back too: the thumbnail is made from the file we just
    # verified, not from a second download of something that may differ.
    return ({"url": url, "type": kind, "bytes": len(data),
             "sha256": hashlib.sha256(data).hexdigest()}, data)


def build():
    previous = {}
    if os.path.exists(OUT):
        with io.open(OUT, encoding="utf-8") as fh:
            for item in json.load(fh).get("items", []):
                previous[item["id"]] = item

    items = []

    # ── Themes ─────────────────────────────────────────────────────────────
    for family, flavour, mode, name, blurb in SCHEMES:
        ident = "theme-%s-%s-%s" % (family, flavour, mode)
        # Offline reuses the COLOURS, which came off the network, and rebuilds
        # the item around them. Reusing the whole item meant a change to a name
        # or a tag silently did not happen on an offline build.
        if OFFLINE and ident in previous:
            colours = {"background": previous[ident]["preview"]["background"],
                       "onBackground": previous[ident]["preview"]["ink"],
                       "surface": previous[ident]["preview"].get("surface", previous[ident]["preview"]["background"]),
                       "primary": previous[ident]["preview"]["colours"][0],
                       "secondary": previous[ident]["preview"]["colours"][1],
                       "tertiary": previous[ident]["preview"]["colours"][2]}
        else:
            colours = scheme_colours(family, flavour, mode)
        items.append({
            "id": ident,
            "section": "themes",
            "name": name,
            "blurb": blurb,
            "author": "caelestia / %s" % family,
            "mode": mode,
            "tags": ["escuro" if mode == "dark" else "claro", family],
            "preview": {"kind": "scheme",
                        "background": colours["background"],
                        "surface": colours.get("surface", colours["background"]),
                        "ink": colours["onBackground"],
                        "colours": [colours["primary"], colours["secondary"],
                                    colours["tertiary"]]},
            "actions": [{"action": "scheme", "name": family,
                         "flavour": flavour, "mode": mode}],
        })

    # ── Decor: wallpapers ──────────────────────────────────────────────────
    for ident, filename, name, blurb, tags in WALLS:
        full = "wall-" + ident
        thumb = full + ".jpg"
        have_thumb = os.path.exists(os.path.join(HERE, "catalog", "thumbs", thumb))
        if OFFLINE and full in previous and have_thumb:
            asset = previous[full]["assets"]["picture"]
        else:
            asset, raw = wallpaper_asset(filename)
            thumb = thumbnail(full, raw, filename)
        items.append({
            "id": full,
            "section": "decor",
            "name": name,
            "blurb": blurb,
            "author": "D3Ext/aesthetic-wallpapers",
            "license": "MIT",
            "source": "https://github.com/D3Ext/aesthetic-wallpapers",
            "tags": tags,
            "preview": {"kind": "image", "thumb": thumb, "asset": "picture"},
            "assets": {"picture": asset},
            "actions": [{"action": "wallpaper", "asset": "picture"}],
        })

    # ── Bar styles ─────────────────────────────────────────────────────────
    for preset, name, blurb in BARS:
        items.append({
            "id": "bar-" + preset.split("-", 1)[1],
            "section": "bars",
            "name": name,
            "blurb": blurb,
            "author": "Genesi",
            "tags": ["barra"],
            "preview": dict({"kind": "bar", "preset": preset},
                            **bar_shape(preset)),
            "actions": [{"action": "bar", "preset": preset}],
        })

    for extra in (lockscreens(), fastfetch(), rices(previous), bundles(),
                  factory()):
        items.extend(extra)

    # The login screens that are downloaded rather than shipped. The map they
    # point into is what makes them data: a card carries a key, and the key
    # resolves -- in the store, and again in the helper, out of the copy under
    # /usr/share that only root can write -- to a URL, a digest and a
    # destination this build decided.
    greeter_specs = {}
    if OFFLINE:
        if os.path.exists(OUT):
            with io.open(OUT, encoding="utf-8") as fh:
                old = json.load(fh)
            greeter_specs = old.get("greeters") or {}
            items.extend([i for i in old.get("items", [])
                          if any(a.get("action") == "greeter"
                                 for a in i.get("actions", []))])
    else:
        greeter_specs, greeter_items = greeters()
        items.extend(greeter_items)

    data = {
        "version": 1,
        "updated": time.strftime("%Y-%m-%d"),
        "sections": SECTIONS,
        "greeters": greeter_specs,
        "items": items,
    }
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with io.open(OUT, "w", encoding="utf-8", newline="\n") as fh:
        json.dump(data, fh, indent=1, ensure_ascii=False, sort_keys=False)
        fh.write("\n")
    print("catalog: %d items across %d sections" % (len(items), len(SECTIONS)))
    for section in SECTIONS:
        count = len([i for i in items if i["section"] == section["id"]])
        print("  %-12s %d" % (section["id"], count))


# ── The text-only shelves ──────────────────────────────────────────────────


HYPRLOCK_BASE = """# %s -- written by Genesi Store.
# hyprlock's own format; edit freely, the store keeps a copy of what was here.

general {
    hide_cursor = true
    grace = 0
    no_fade_in = false
}

background {
    monitor =
    path = %s
    blur_passes = %d
    blur_size = %d
    brightness = %s
    contrast = 1.0
    vibrancy = 0.17
}

input-field {
    monitor =
    size = 320, 52
    outline_thickness = 2
    dots_size = 0.24
    dots_spacing = 0.3
    dots_center = true
    outer_color = %s
    inner_color = %s
    font_color = %s
    fade_on_empty = false
    placeholder_text = <i>%s</i>
    hide_input = false
    rounding = %d
    position = 0, -90
    halign = center
    valign = center
}

label {
    monitor =
    text = $TIME
    font_size = %d
    font_family = %s
    color = %s
    position = 0, 160
    halign = center
    valign = center
}

label {
    monitor =
    text = %s
    font_size = 16
    font_family = %s
    color = %s
    position = 0, 96
    halign = center
    valign = center
}
"""


def lock_item(ident, name, blurb, tags, text, preview):
    """A session lock: the config file, and the locker it needs to exist."""
    return {
        "id": "lock-" + ident,
        "section": "lockscreens",
        "name": name,
        "blurb": blurb,
        "family": "session",
        "author": "Genesi",
        "tags": ["sessão"] + tags,
        "preview": preview,
        "actions": [
            {"action": "package", "name": "hyprlock", "binary": "hyprlock"},
            # The one that was missing. hyprlock is not a daemon -- it is run
            # once, to lock the screen now -- and the Lock button emits a
            # logind signal rather than running anything. hypridle is what
            # listens for the signal and runs the locker, and without it every
            # card on this shelf applied cleanly and changed nothing visible.
            {"action": "package", "name": "hypridle", "binary": "hypridle"},
            {"action": "file", "path": "~/.config/hypr/hyprlock.conf",
             "text": text},
            {"action": "locker"},
        ],
    }


def lockscreens():
    out = []
    out.append(lock_item(
        "wallpaper", "Papel de parede", "O seu papel de parede, desfocado.",
        ["desfoque"],
        HYPRLOCK_BASE % ("Papel de parede", "screenshot", 3, 8, "0.7",
                         "rgba(143, 214, 171, 0.9)", "rgba(20, 28, 24, 0.75)",
                         "rgba(233, 245, 238, 1.0)", "senha", 14, 96,
                         "Rubik", "rgba(233, 245, 238, 0.95)",
                         "$USER", "Rubik", "rgba(143, 214, 171, 0.85)"),
        {"kind": "lock", "background": "#14241c", "accent": "#8fd6ab",
         "thumb": "wall-forest-dark.jpg", "blur": True}))
    out.append(lock_item(
        "clean", "Limpa", "Fundo sólido, relógio grande, nada mais.",
        ["minimalista"],
        HYPRLOCK_BASE % ("Limpa", "", 0, 0, "1.0",
                         "rgba(143, 214, 171, 0.8)", "rgba(16, 20, 18, 0.9)",
                         "rgba(240, 244, 241, 1.0)", "digite a senha", 8, 120,
                         "Rubik", "rgba(240, 244, 241, 0.95)",
                         "", "Rubik", "rgba(143, 214, 171, 0.8)"),
        {"kind": "lock", "background": "#101412", "accent": "#8fd6ab"}))
    out.append(lock_item(
        "night", "Noite", "Escuro de verdade, para não acordar ninguém.",
        ["escuro", "oled"],
        HYPRLOCK_BASE % ("Noite", "screenshot", 4, 10, "0.35",
                         "rgba(120, 160, 140, 0.7)", "rgba(0, 0, 0, 0.85)",
                         "rgba(200, 220, 208, 1.0)", "senha", 20, 84,
                         "Rubik", "rgba(200, 220, 208, 0.9)",
                         "$TIME", "Rubik", "rgba(120, 160, 140, 0.7)"),
        {"kind": "lock", "background": "#000000", "accent": "#78a08c",
         "thumb": "wall-oled-mountains.jpg", "blur": True}))
    out.append(lock_item(
        "terminal", "Terminal", "Monoespaçada, como um prompt.",
        ["mono", "retro"],
        HYPRLOCK_BASE % ("Terminal", "screenshot", 1, 4, "0.5",
                         "rgba(143, 214, 171, 1.0)", "rgba(10, 14, 12, 0.9)",
                         "rgba(143, 214, 171, 1.0)", "login:", 2, 72,
                         "CaskaydiaCove Nerd Font", "rgba(143, 214, 171, 1.0)",
                         "$USER@$(hostname)", "CaskaydiaCove Nerd Font",
                         "rgba(143, 214, 171, 0.7)"),
        {"kind": "lock", "background": "#0a0e0c", "accent": "#8fd6ab",
         "thumb": "wall-ink-wave.jpg", "blur": True, "mono": True}))

    # ── The other lock: the screen BEFORE the session ──────────────────────
    #
    # Different machinery entirely -- SDDM, running as root, before anyone has
    # logged in -- so these are their own family, and the app says so. Only
    # themes that are already installed are offered: a login screen pointed at
    # a theme that is not there is a login screen that does not come up, and
    # that is not a thing to find out by rebooting.
    # Genesi's own, whose picture is a render of the very QML this package
    # installs -- made by ci/sddm-shot, kept in sddm/preview.png, which is also
    # the Screenshot= the theme's metadata has always claimed to have.
    #
    # And Breeze, which is not really a theme here: it is the way OUT. Picking
    # it deletes the drop-in, so the login screen goes back to whatever the
    # system decides rather than to whatever this tool last saw.
    #
    # SDDM's other stock themes used to be on this shelf and are not any more.
    # They shipped no picture, so they were grey cards among thirty with real
    # screenshots -- and a grey card is the thing this whole shelf was rebuilt
    # to stop being.
    genesi_shot = os.path.join(HERE, "sddm", "preview.png")
    thumb = ""
    if os.path.exists(genesi_shot):
        with io.open(genesi_shot, "rb") as fh:
            thumb = thumbnail("greeter-genesi", fh.read(), "preview.png")
    for ident, theme, name, blurb, preview in (
            ("genesi", "genesi", "Genesi",
             "A nossa: a marca, a hora e um campo só. Vem com a loja.",
             {"kind": "login", "theme": "genesi", "background": "#070c09",
              "accent": "#39d98a", "thumb": thumb}),
            ("breeze", "breeze", "A padrão do sistema",
             "Volta para a tela que o Genesi instala. É o caminho de volta "
             "de qualquer uma das outras.",
             {"kind": "login", "theme": "breeze", "background": "#1b1e20",
              "accent": "#8ab4d8"})):
        out.append({
            "id": "login-" + ident,
            "section": "login",
            "name": name,
            "blurb": blurb,
            "family": "login",
            "author": "Genesi" if theme == "genesi" else "SDDM",
            "tags": ["login", "antes da sessão"],
            "needs_root": True,
            "preview": preview,
            "actions": [{"action": "login", "theme": theme}],
        })
    return out


IMAGE_BLURB = ("Uma foto no lugar do desenho, em sixel. Precisa de um terminal que\n               desenhe imagens: o foot, que e o padrao do Genesi, desenha.")


FASTFETCH_HEAD = ('{\n  "$schema": '
                  '"https://github.com/fastfetch-cli/fastfetch/raw/dev/doc/json_schema.json",\n')


BAR_PRESET_DIR = os.path.join(
    os.path.dirname(HERE), "genesi-caelestia-settings", "bar-presets")


def bar_shape(preset):
    """What one bar preset actually looks like, read from the preset itself.

    Fifteen cards drawn from one generic picture are fifteen identical cards,
    which is what this shelf was: you could not tell the thin one from the
    wide one, or the one with a clock at the top from the one with a logo.
    Everything needed to tell them apart is already in the preset file --
    which modules, in what order, how wide, how far apart, whether things sit
    on pills -- so the picture is read from there rather than invented.

    Read at BUILD time, not by the app: the app would have to go find the
    settings package at runtime, and a card that cannot draw itself without
    another package installed is a card that is blank on somebody's machine.
    """
    path = os.path.join(BAR_PRESET_DIR, preset + ".json")
    if not os.path.exists(path):
        raise SystemExit("the bar preset %s is not in %s" % (preset, BAR_PRESET_DIR))
    with io.open(path, encoding="utf-8") as fh:
        data = json.load(fh)
    bar = data.get("bar", data)
    entries = [e.get("id") for e in (bar.get("entries") or []) if e.get("id")]
    if not entries:
        raise SystemExit("the bar preset %s lists no modules" % preset)

    def opt(name, key):
        block = bar.get(name)
        return bool(isinstance(block, dict) and block.get(key))

    return {
        "entries": entries,
        # The real numbers, so a thin bar draws thin. caelestia's own default
        # when a preset does not say is 40 wide with 12 between things.
        "width": bar.get("width", 40),
        "spacing": bar.get("spacing", 12),
        "pills": opt("clock", "background") or opt("tray", "background"),
        "date": opt("clock", "showDate"),
        "windows": opt("workspaces", "showWindows"),
        "trail": opt("workspaces", "activeTrail"),
        "compact": opt("activeWindow", "compact") or opt("tray", "compact"),
        "hidden": bar.get("persistent") is False or bool(bar.get("showOnHover")),
    }


def factory():
    """One card per shelf that puts it back the way the machine shipped.

    Revert, on an item's page, undoes THAT item -- it needs to know what was
    there before, so it only exists for something the store itself applied.
    That is the wrong tool for "I have been clicking around for an hour and I
    want my desktop back", which is the state somebody is actually in when
    they go looking for this.

    So these undo the CATEGORY, from whatever it is now, without needing to
    remember how it got there. For the shelves that are a config file, factory
    means deleting the file the store wrote: the packaged default is what gets
    read once nothing is overriding it, which is the same thing a fresh
    install has.

    Deliberately not on Decoration: there is no single wallpaper the machine
    ships with, so a card promising one would be making it up.
    """
    def card(ident, section, name, blurb, preview, actions, needs_root=False):
        card = {
            "id": "default-" + ident,
            "section": section,
            "name": name,
            "blurb": blurb,
            "family": "factory",
            "author": "Genesi",
            "tags": ["padrão", "de fábrica"],
            "preview": preview,
            "actions": actions,
        }
        # Putting the login screen back is still changing /etc, so it still
        # asks for a password and the card still has to say so.
        if needs_root:
            card["needs_root"] = True
        return card

    plain = {"kind": "scheme", "colours": ["#39d98a", "#8fd6ab", "#1d2a22"],
             "background": "#0c120f", "surface": "#16211b", "ink": "#e9f5ee"}

    return [
        card("themes", "themes", "Como vem de fábrica",
             "A paleta que segue o seu papel de parede, que é a do Genesi novo.",
             plain, [{"action": "scheme", "name": "dynamic"}]),

        card("login", "login", "Como vem de fábrica",
             "A tela de login do Genesi, sem nada baixado por cima.",
             {"kind": "login", "theme": "genesi", "accent": "#39d98a"},
             [{"action": "login", "theme": "genesi"}], needs_root=True),

        # Deleting the file is the whole undo: with no hyprlock.conf of its
        # own the machine is back to having no session lock configured, and
        # `unlocker` stops the watcher the store started.
        card("lockscreens", "lockscreens", "Como vem de fábrica",
             "Tira o bloqueio que a loja configurou e para o vigia dele.",
             {"kind": "lock", "accent": "#8fd6ab", "background": "#0c120f"},
             [{"action": "restore", "path": "~/.config/hypr/hyprlock.conf"},
              {"action": "unlocker"}]),

        card("fastfetch", "fastfetch", "Como vem de fábrica",
             "Volta para o cartão do Genesi que aparece ao abrir o terminal.",
             {"kind": "terminal",
              "lines": ["genesi@genesi", "sistema  Genesi OS",
                        "sessão   Hyprland"]},
             [{"action": "restore",
               "path": "~/.config/fastfetch/config.jsonc"}]),

        card("bars", "bars", "Como vem de fábrica",
             "O arranjo de barra que vem no Genesi novo.",
             {"kind": "bar", "background": "#0c120f", "surface": "#16211b",
              "ink": "#e9f5ee", "accent": "#39d98a"},
             [{"action": "bar", "preset": "10-padrao"}]),
    ]


def fastfetch():
    def item(ident, name, blurb, tags, body):
        out = {
            "id": "fetch-" + ident,
            "section": "fastfetch",
            "name": name,
            "blurb": blurb,
            "author": "Genesi",
            "tags": tags,
            # The logo is the biggest difference between one fastfetch and the
            # next, and the card was not drawing it at all -- so four options
            # that look nothing alike in a terminal looked identical here.
            "preview": {"kind": "terminal", "lines": body["preview"],
                        "logo": body.get("logo", "full"),
                        "keyed": body.get("keyed", True)},
            "actions": [{"action": "file",
                         "path": "~/.config/fastfetch/config.jsonc",
                         "text": body["text"]}],
        }
        if body.get("asset"):
            out["assets"] = {"picture": body["asset"]}
        return out

    compact = FASTFETCH_HEAD + """  "logo": { "type": "small", "padding": { "top": 1, "right": 2 } },
  "display": { "separator": "  " },
  "modules": [
    { "type": "title", "format": "{user-name}@{host-name}" },
    "separator",
    { "type": "os", "key": "sistema" },
    { "type": "kernel", "key": "kernel" },
    { "type": "wm", "key": "sessão" },
    { "type": "memory", "key": "memoria" },
    { "type": "uptime", "key": "ligado ha" }
  ]
}
"""
    full = FASTFETCH_HEAD + """  "logo": { "padding": { "top": 2, "right": 3 } },
  "display": { "separator": "  ", "color": { "keys": "green" } },
  "modules": [
    "title", "separator",
    { "type": "os", "key": "sistema" },
    { "type": "host", "key": "maquina" },
    { "type": "kernel", "key": "kernel" },
    { "type": "packages", "key": "pacotes" },
    { "type": "shell", "key": "shell" },
    { "type": "wm", "key": "sessão" },
    { "type": "terminal", "key": "terminal" },
    { "type": "cpu", "key": "cpu" },
    { "type": "gpu", "key": "gpu" },
    { "type": "memory", "key": "memoria" },
    { "type": "disk", "key": "disco" },
    { "type": "uptime", "key": "ligado ha" },
    "break", "colors"
  ]
}
"""
    bare = FASTFETCH_HEAD + """  "logo": { "type": "none" },
  "display": { "separator": " " },
  "modules": [
    { "type": "custom", "format": "  genesi" },
    { "type": "os", "key": " " },
    { "type": "kernel", "key": " " },
    { "type": "memory", "key": " " },
    { "type": "uptime", "key": " " }
  ]
}
"""
    green = FASTFETCH_HEAD + """  "logo": { "source": "arch", "color": { "1": "green", "2": "green" } },
  "display": { "separator": "  ", "color": { "keys": "green", "title": "green" } },
  "modules": [
    { "type": "title", "format": "{user-name} em {host-name}" },
    { "type": "custom", "format": "\\u001b[32m-----------------------------\\u001b[0m" },
    { "type": "os", "key": "sistema" },
    { "type": "wm", "key": "sessão" },
    { "type": "cpu", "key": "cpu" },
    { "type": "memory", "key": "memoria" },
    { "type": "disk", "key": "disco" },
    { "type": "uptime", "key": "ligado ha" }
  ]
}
"""
    # An image where the ASCII art goes. `sixel` is the protocol foot speaks --
    # Genesi's default terminal, picked because it needs no OpenGL and so
    # survives a VM -- and it is NOT kitty's, so a config copied from a kitty
    # setup shows nothing here.
    #
    # The picture is downloaded with the card and its path is substituted in,
    # rather than named as a fixed location: pointing at a file that may not
    # be there prints an error where the logo should be.
    shot_asset, _ = wallpaper_asset("dark_forest.png")

    image_big = FASTFETCH_HEAD + """  "logo": {
    "type": "sixel",
    "source": "{{asset:picture}}",
    "width": 34,
    "padding": { "top": 1, "right": 3 }
  },
  "display": { "separator": "  ", "color": { "keys": "green" } },
  "modules": [
    { "type": "title", "format": "{user-name}@{host-name}" },
    "separator",
    { "type": "os", "key": "sistema" },
    { "type": "kernel", "key": "kernel" },
    { "type": "wm", "key": "sessão" },
    { "type": "cpu", "key": "cpu" },
    { "type": "gpu", "key": "gpu" },
    { "type": "memory", "key": "memoria" },
    { "type": "uptime", "key": "ligado ha" }
  ]
}
"""

    image_small = FASTFETCH_HEAD + """  "logo": {
    "type": "sixel",
    "source": "{{asset:picture}}",
    "width": 18,
    "padding": { "top": 1, "right": 2 }
  },
  "display": { "separator": "  " },
  "modules": [
    { "type": "title", "format": "{user-name}" },
    { "type": "os", "format": "{name}" },
    { "type": "wm", "format": "{name}" },
    { "type": "uptime" }
  ]
}
"""

    return [
        item("compact", "Compacto", "Cinco linhas e o logo pequeno.",
             ["curto"], {"text": compact, "logo": "small",
                         "preview": ["matheus@genesi", "sistema  Genesi OS",
                                     "sessao   Hyprland", "memoria  6.2 / 16 GiB"]}),
        item("full", "Completo", "Tudo que dá para contar sobre a máquina.",
             ["longo"], {"text": full, "logo": "full",
                         "preview": ["sistema  Genesi OS x86_64",
                                     "cpu      Ryzen 7 / 16 threads",
                                     "gpu      RTX 3050", "disco    712 / 954 GiB"]}),
        item("bare", "Sem logo", "Só texto, para quem abre muitos terminais.",
             ["minimalista"], {"text": bare, "logo": "none", "keyed": False,
                               "preview": ["  genesi", "  Genesi OS",
                                           "  6.14.2", "  1d 3h"]}),
        item("green", "Verde", "As cores da casa no prompt.",
             ["verde"], {"text": green, "logo": "full",
                         "preview": ["matheus em genesi",
                                     "-----------------------------",
                                     "sistema  Genesi OS", "sessao   Hyprland"]}),
        item("image", "Com imagem", IMAGE_BLURB, ["imagem", "sixel"],
             {"text": image_big, "logo": "image", "asset": shot_asset,
              "preview": ["sistema  Genesi OS", "sessão   Hyprland",
                          "cpu      Ryzen 7", "memoria  6.2 / 16 GiB"]}),
        item("image-small", "Com imagem (pequena)", IMAGE_BLURB,
             ["imagem", "sixel", "curto"],
             {"text": image_small, "logo": "image", "asset": shot_asset,
              "preview": ["genesi", "Genesi OS", "Hyprland", "1d 3h"]}),
    ]


def rices(previous):
    """A whole desktop at once: colours, wallpaper, bar and lock together."""
    def rice(ident, name, blurb, tags, scheme, wall, bar, lock, colour):
        return {
            "id": "rice-" + ident,
            "section": "rices",
            "name": name,
            "blurb": blurb,
            "author": "Genesi",
            "tags": tags,
            "preview": {"kind": "desktop", "accent": colour,
                        "thumb": "wall-%s.jpg" % wall,
                        "scheme": "theme-" + scheme},
            "includes": ["theme-" + scheme, "wall-" + wall, "bar-" + bar,
                         "lock-" + lock],
            "actions": [],
        }

    made = [
        rice("floresta-viva", "Floresta Viva",
             "Verde fechado, barra rente, bloqueio desfocado.",
             ["verde", "natureza"], "everforest-medium-dark", "forest-dark",
             "borda", "wallpaper", "#a7c080"),
        rice("orvalho", "Orvalho",
             "Verde claro da casa sobre água parada.",
             ["verde", "calmo"], "caelestia-default-dark", "lake",
             "arejado", "clean", "#8fd6ab"),
        rice("noite-baixa", "Noite Baixa",
             "Preto real, barra fina, nada brilhando.",
             ["escuro", "oled"], "darkgreen-hard-dark", "oled-mountains",
             "fio", "night", "#4f8f6a"),
        rice("terra", "Terra",
             "Gruvbox, cidade retrô e barra densa.",
             ["quente", "retro"], "gruvbox-medium-dark", "gruvbox-city",
             "painel", "terminal", "#d79921"),
        rice("meia-noite", "Meia-Noite",
             "Tokyo Night com neon e barra centralizada.",
             ["escuro", "neon"], "tokyonight-medium-dark", "neocity",
             "centrado", "night", "#7aa2f7"),
        rice("papel", "Papel",
             "Claro, quieto, para trabalhar de dia.",
             ["claro", "minimalista"], "catppuccin-latte-light", "minimal-c",
             "limpo", "clean", "#8839ef"),
    ]
    return made


def bundles():
    """Two or three things that go together, and say what they will change."""
    return [
        {
            "id": "bundle-primeira-troca",
            "section": "bundles",
            "name": "Primeira Troca",
            "blurb": "O básico para o desktop deixar de ser o padrão: cor, "
                     "papel de parede e uma barra que respira.",
            "author": "Genesi",
            "tags": ["comeco"],
            "preview": {"kind": "desktop", "accent": "#8fd6ab",
                        "thumb": "wall-nature.jpg"},
            "includes": ["theme-caelestia-default-dark", "wall-nature",
                         "bar-arejado"],
            "actions": [],
        },
        {
            "id": "bundle-terminal",
            "section": "bundles",
            "name": "Vida no Terminal",
            "blurb": "Fastfetch completo, bloqueio monoespaçado e uma barra "
                     "densa: para quem vive no prompt.",
            "author": "Genesi",
            "tags": ["terminal"],
            "preview": {"kind": "desktop", "accent": "#8fd6ab",
                        "thumb": "wall-ink-wave.jpg"},
            "includes": ["fetch-full", "lock-terminal", "bar-informativo",
                         "wall-ink-wave"],
            "actions": [],
        },
        {
            "id": "bundle-descanso",
            "section": "bundles",
            "name": "Descanso",
            "blurb": "Claro de dia, sem barulho visual: tema claro, papel "
                     "minimalista e barra limpa.",
            "author": "Genesi",
            "tags": ["claro", "calmo"],
            "preview": {"kind": "desktop", "accent": "#40a02b",
                        "thumb": "wall-minimal-c.jpg"},
            "includes": ["theme-everforest-medium-light", "wall-minimal-c",
                         "bar-limpo"],
            "actions": [],
        },
    ]


# ── The OTHER lock: login screens somebody else wrote ──────────────────────
#
# The session lock above is a config file. These are whole Qt applications
# that run as root, before anybody has logged in, and if one of them fails to
# draw the machine has no way in but a text console. So the rules here are
# stricter than anywhere else in this file:
#
#   * Pinned to a COMMIT, never to a branch. "main" is whatever somebody
#     pushed this morning.
#   * Refused unless the theme's own metadata says QtVersion=6 and its QML
#     imports are all Qt6. Half the beautiful SDDM themes on GitHub are Qt5
#     and would be a black screen on Genesi -- that is a build failure here,
#     not a discovery at 3am.
#   * The QML modules each theme imports are read out of its own source and
#     recorded, so the helper installs them BEFORE switching the greeter.
#   * What is recorded is a digest of the CONTENT, not of the tarball. GitHub
#     builds those archives on demand and re-compressed them once already,
#     which changed every checksum in the world without changing one file.
#
# Every one of these is GPL-3.0 or MIT, credited by name and repository in the
# card, and installed unmodified but for the one line that selects a variant.

GREETER_REPOS = {
    # key: (repository, the commit this catalogue was built against)
    "astronaut": ("Keyitdev/sddm-astronaut-theme",
                  "abb3163c724935af888ba5ea9ac0c4f22afd8048"),
    "caelestia": ("ItsABigIgloo/caelestia-sddm",
                  "7843c0f38de1e4f8606976ae0983536bf8ed4c76"),
    "silent": ("uiriansan/SilentSDDM",
               "73380d331fe0f8b8a3b17991bb917a0d438a4d34"),
    "echo": ("xCaptaiN09/echo-sddm",
             "e004121450ff71050d3d76a998b86eafdbb6bf47"),
    "pixie": ("xCaptaiN09/pixie-sddm",
              "1e1a863761f742e8d509d569382b17c112e29fdc"),
    "whereis": ("stepanzubkov/where-is-my-sddm-theme",
                "2fddf85ec80ff02a8e20fdcba51a30b436d76e6c"),
    "hypr": ("ADIOR-enigma/hypr-sddm",
             "52fd4a538fabea2331d9b9f956c2497ff5f9102c"),
}

# key, repo, subpath inside the archive, directory it installs as,
# who wrote it, licence
GREETERS = [
    ("astronaut", "astronaut", "", "genesi-astronaut",
     "keyitdev", "GPL-3.0-or-later"),
    ("caelestia-locklike", "caelestia", "themes/locklike",
     "genesi-caelestia-locklike", "AkhiLeith", "GPL-3.0-or-later"),
    ("caelestia-minimalist", "caelestia", "themes/minimalistV2",
     "genesi-caelestia-minimalist", "Haikalllp", "GPL-3.0-or-later"),
    ("silent", "silent", "", "genesi-silent", "uiriansan", "GPL-3.0-or-later"),
    ("echo", "echo", "", "genesi-echo", "xCaptaiN09", "MIT"),
    ("pixie", "pixie", "", "genesi-pixie", "xCaptaiN09", "MIT"),
    ("whereis", "whereis", "where_is_my_sddm_theme", "genesi-whereis",
     "stepanzubkov", "MIT"),
    # Note what this one is NOT: it does not read the running caelestia shell
    # the way caelestia-sddm does. It is a standalone theme that looks like
    # hyprlock, with its own wallpaper and its own palette in theme.conf. The
    # repository also carries a matugen config for recolouring it from your
    # wallpaper, which needs the install script in sudoers -- so the store
    # does not use it, and the theme works without it.
    ("hypr", "hypr", "", "genesi-hypr", "adior_enigmac", "MIT"),
]

# What a QML import costs in packages. A theme that imports a module the
# machine does not have does not fall back to something plainer -- it fails to
# load, and SDDM shows nothing.
MODULE_PACKAGES = {
    "QtQuick.VirtualKeyboard": "qt6-virtualkeyboard",
    "QtMultimedia": "qt6-multimedia",
    "Qt5Compat.GraphicalEffects": "qt6-5compat",
    "QtQuick.Shapes": "qt6-declarative",
    "QtQuick.Effects": "qt6-declarative",
    "QtQuick.Controls": "qt6-declarative",
    "QtQuick.Layouts": "qt6-declarative",
    "QtQuick.Window": "qt6-declarative",
    "QtQuick": "qt6-declarative",
    "QtQml": "qt6-declarative",
    "SddmComponents": "",          # comes with sddm itself
}

# The biggest screenshot in the catalogue is 2.7 MB. Eight is room to grow
# and still small enough that a card cannot be used to push a file at anybody.
MAX_SHOT_BYTES = 8 * 1024 * 1024

# Imports that only exist in Qt5. Seeing one means the theme was never ported,
# and installing it would be handing somebody a machine they cannot log into.
QT5_ONLY = ("QtGraphicalEffects", "QtQuick.Controls.Styles")

GREETER_ITEMS = [
    # id, greeter key, config file inside the theme (or ""), name, blurb,
    # tags, where the picture comes from
    ("astronaut", "astronaut", "Themes/astronaut.conf", "Astronauta",
     "Um astronauta à deriva, e o campo de senha no meio do espaço.",
     ["espaço", "animado"], "url:astronaut.png"),
    ("astronaut-black-hole", "astronaut", "Themes/black_hole.conf",
     "Buraco Negro", "Fundo animado engolindo a luz. O mais pesado dos dez.",
     ["espaço", "animado", "escuro"], "url:black_hole.png"),
    ("astronaut-cyberpunk", "astronaut", "Themes/cyberpunk.conf", "Cyberpunk",
     "Neon rosa e ciano, chuva na cidade.", ["neon", "animado"],
     "url:cyberpunk.png"),
    ("astronaut-hyprland", "astronaut", "Themes/hyprland_kath.conf",
     "Hyprland", "A garota do Hyprland, animada.", ["anime", "animado"],
     "url:frame_hyprland_kath.png"),
    ("astronaut-jake", "astronaut", "Themes/jake_the_dog.conf", "Jake",
     "Hora de aventura na tela de login.", ["cartoon", "animado"],
     "url:frame_jake_the_dog.png"),
    ("astronaut-japanese", "astronaut", "Themes/japanese_aesthetic.conf",
     "Japonesa", "Torii, montanha e um degradê de fim de tarde.",
     ["paisagem"], "url:japanese_aesthetic.png"),
    ("astronaut-sakura", "astronaut", "Themes/pixel_sakura.conf",
     "Sakura (animada)", "Pétalas caindo em pixel art, em movimento.",
     ["pixel", "animado"], "url:frame_pixel_sakura.png"),
    ("astronaut-sakura-still", "astronaut", "Themes/pixel_sakura_static.conf",
     "Sakura (parada)", "A mesma cena em pixel art, sem animação -- mais leve.",
     ["pixel", "leve"], "url:pixel_sakura_static.png"),
    ("astronaut-hacker", "astronaut",
     "Themes/post-apocalyptic_hacker.conf", "Hacker",
     "Terminal verde sobre ruína. Mono e sujo, do jeito certo.",
     ["terminal", "verde"], "url:post-apocalyptic_hacker.png"),
    ("astronaut-purple-leaves", "astronaut", "Themes/purple_leaves.conf",
     "Folhas Roxas", "Folhagem roxa e um campo discreto embaixo.",
     ["natureza", "roxo"], "url:purple_leaves.png"),

    ("caelestia-locklike", "caelestia-locklike", "", "Caelestia Locklike",
     "A tela de login igual ao bloqueio do caelestia: relógio enorme, "
     "citação, avatar. É o desktop do Genesi antes de entrar nele.",
     ["caelestia", "combina"], "url:caelestia-locklike"),
    ("caelestia-minimalist", "caelestia-minimalist", "",
     "Caelestia Minimalist", "A mesma família, reduzida ao relógio e ao campo.",
     ["caelestia", "minimalista"], "url:caelestia-minimalist"),

    ("silent", "silent", "configs/default.conf", "Silent",
     "Um cartão de vidro no meio da tela. O mais bem acabado da lista.",
     ["vidro", "moderno"], "tar:docs/previews/default.png"),
    ("silent-left", "silent", "configs/default-left.conf", "Silent (esquerda)",
     "O mesmo cartão, encostado à esquerda.", ["vidro", "moderno"],
     "tar:docs/previews/default-left.png"),
    ("silent-right", "silent", "configs/default-right.conf",
     "Silent (direita)", "O mesmo cartão, encostado à direita.",
     ["vidro", "moderno"], "tar:docs/previews/default-right.png"),
    ("silent-mocha", "silent", "configs/catppuccin-mocha.conf",
     "Silent Catppuccin Mocha", "Catppuccin escuro, o de sempre.",
     ["catppuccin", "escuro"], "tar:docs/previews/catppuccin-mocha.png"),
    ("silent-macchiato", "silent", "configs/catppuccin-macchiato.conf",
     "Silent Catppuccin Macchiato", "Catppuccin um tom acima do mocha.",
     ["catppuccin", "escuro"], "tar:docs/previews/catppuccin-macchiato.png"),
    ("silent-frappe", "silent", "configs/catppuccin-frappe.conf",
     "Silent Catppuccin Frappé", "Catppuccin morno.", ["catppuccin"],
     "tar:docs/previews/catppuccin-frappe.png"),
    ("silent-latte", "silent", "configs/catppuccin-latte.conf",
     "Silent Catppuccin Latte", "Catppuccin claro, para quem usa tema claro.",
     ["catppuccin", "claro"], "tar:docs/previews/catppuccin-latte.png"),
    ("silent-everforest", "silent", "configs/everforest.conf",
     "Silent Everforest", "Verde de floresta, que é a cor da casa.",
     ["everforest", "verde"], "tar:docs/previews/everforest.png"),
    ("silent-nord", "silent", "configs/nord.conf", "Silent Nord",
     "Azul frio do Nord.", ["nord", "azul"], "tar:docs/previews/nord.png"),
    ("silent-ken", "silent", "configs/ken.conf", "Silent Ken",
     "Com vídeo de fundo. Bonito, e o mais pesado da prateleira.",
     ["vídeo", "animado"], "tar:docs/previews/ken.png"),
    ("silent-rei", "silent", "configs/rei.conf", "Silent Rei",
     "Também com vídeo de fundo.", ["vídeo", "animado", "anime"],
     "tar:docs/previews/rei.png"),

    ("echo", "echo", "", "Echo",
     "Um terminal do macOS com o log de boot correndo dentro. "
     "Você digita a senha no prompt.", ["terminal", "mono"],
     "tar:assets/screenshots/Screenshot_1.png"),
    ("pixie", "pixie", "", "Pixie",
     "Material You: relógio empilhado, cantos macios, cor de Pixel.",
     ["material", "limpo"], "tar:screenshots/login_screen.png"),

    ("whereis", "whereis", "theme.conf", "Cadê meu tema?",
     "Fundo preto e a senha em letras gigantes. Nada mais na tela.",
     ["minimalista", "rápido"], "tar:screenshots/classic.png"),
    ("whereis-blue", "whereis", "example_configs/blue.conf",
     "Cadê meu tema? (azul)", "O mesmo nada, em azul.",
     ["minimalista", "azul"], "tar:screenshots/blue.png"),
    ("whereis-grey", "whereis", "example_configs/grey.conf",
     "Cadê meu tema? (cinza)", "O mesmo nada, em cinza.",
     ["minimalista"], "tar:screenshots/grey.png"),
    ("whereis-nord", "whereis", "example_configs/nord.conf",
     "Cadê meu tema? (nord)", "O mesmo nada, com a paleta Nord.",
     ["minimalista", "nord"], "tar:screenshots/nord.png"),
    ("whereis-rose", "whereis", "example_configs/rose-pine-moon.conf",
     "Cadê meu tema? (rosé pine)", "O mesmo nada, em rosé pine moon.",
     ["minimalista", "rosa"], "tar:screenshots/rose-pine-moon.png"),
    ("whereis-tree", "whereis", "example_configs/tree.conf",
     "Cadê meu tema? (árvore)", "Com uma foto atrás, para provar que dá.",
     ["minimalista", "foto"], "tar:screenshots/tree.png"),
    ("hypr", "hypr", "", "Hypr",
     "O jeitão do hyprlock na tela de login: relógio empilhado, cartão "
     "no meio, paleta fixa. Não segue o seu papel de parede.",
     ["minimalista", "escuro"], "tar:screenshot.png"),
]

# The pictures that are not in the repository itself. The astronaut previews
# live in the author's screenshots repository; the two caelestia ones are the
# images from its README.
GREETER_PICTURES = {
    "caelestia-locklike":
        "https://github.com/user-attachments/assets/"
        "ef2c973d-c723-4a71-b535-04951a2c3130",
    "caelestia-minimalist":
        "https://github.com/user-attachments/assets/"
        "02207bd5-fa7b-4312-9ff2-583f57fc5f18",
}
# Pinned to a commit for the same reason the themes are: this URL is now in
# the catalogue and fetched on the user's machine, so a branch here would mean
# the picture on the card can change under us without the catalogue moving.
# (The second "master" is a directory in that repository, not a ref.)
ASTRONAUT_SHOTS = ("https://raw.githubusercontent.com/Keyitdev/screenshots/"
                   "ebe29f1f9efbb055687cb918a284d7aee62921e3"
                   "/sddm-astronaut-theme/master/")

# Which greeter comes out of which archive: three of them share two downloads.
REPO_OF = {key: repo for key, repo, _, _, _, _ in GREETERS}

_ARCHIVES = {}


def greeter_archive(repo_key):
    """The tarball, downloaded once however many themes come out of it."""
    if repo_key not in _ARCHIVES:
        repo, ref = GREETER_REPOS[repo_key]
        url = "https://codeload.github.com/%s/tar.gz/%s" % (repo, ref)
        print("  fetching %s" % url)
        data = get(url, binary=True)
        if not data.startswith(b"\x1f\x8b"):
            raise SystemExit("%s did not answer with a gzip archive" % url)
        _ARCHIVES[repo_key] = (url, data)
    return _ARCHIVES[repo_key]


def archive_root(repo_key):
    repo, ref = GREETER_REPOS[repo_key]
    return "%s-%s" % (repo.split("/")[1], ref)


def greeter_members(repo_key):
    import tarfile
    _, data = greeter_archive(repo_key)
    return tarfile.open(fileobj=io.BytesIO(data), mode="r:gz")


def tree_digest_of(repo_key, subpath):
    """The same digest genesi-store-helper computes after it unpacks.

    Every regular file under the subtree, by relative path in sorted order,
    path then bytes. Not the archive's checksum: see the note at the top of
    this section, and ci/store-test.py, which runs this function and the
    helper's over the same tree and fails if they ever disagree.
    """
    prefix = "/".join(x for x in (archive_root(repo_key), subpath) if x)
    files = {}
    with greeter_members(repo_key) as tar:
        for member in tar:
            if not member.isfile():
                continue
            name = member.name
            if name != prefix and not name.startswith(prefix + "/"):
                continue
            rel = name[len(prefix):].lstrip("/")
            files[rel] = tar.extractfile(member).read()
    if not files:
        raise SystemExit("nothing under %s in the %s archive"
                         % (prefix, repo_key))
    digest = hashlib.sha256()
    for rel in sorted(files):
        digest.update(rel.encode("utf-8"))
        digest.update(b"\0")
        digest.update(files[rel])
        digest.update(b"\0")
    return digest.hexdigest(), files


def greeter_needs(files):
    """What this theme's own QML says it cannot run without."""
    needs = set()
    for rel, blob in files.items():
        if not rel.endswith(".qml"):
            continue
        text = blob.decode("utf-8", "replace")
        for line in text.splitlines():
            line = line.strip()
            if not line.startswith("import "):
                continue
            module = line.split()[1]
            for bad in QT5_ONLY:
                if module == bad or module.startswith(bad + "."):
                    raise SystemExit(
                        "%s imports %s, which is Qt5 only -- on Genesi that "
                        "theme is a black screen at boot" % (rel, module))
            for known, package in MODULE_PACKAGES.items():
                if module == known or module.startswith(known + "."):
                    if package:
                        needs.add(package)
                    break
    if any(rel.endswith(".svg") for rel in files):
        needs.add("qt6-svg")
    return sorted(needs)


def greeter_confs(files):
    return sorted(rel for rel in files if rel.endswith(".conf"))


def greeter_picture(item_id, key, where):
    """Where the screenshot IS, verified now and fetched on the machine.

    These pictures are not ours. They are the authors' screenshots, and some
    of what is in them is not even theirs -- the astronaut wallpapers are
    described by their own README as "copied from one user to another", and
    two of them are frames of a cartoon and of a commercial game. Shipping
    them inside a Genesi package would be Genesi redistributing that. Naming
    them is not: the picture comes from the same place the theme does, pinned
    to the same kind of commit, checked against the same kind of digest.

    So this downloads the file ONCE, at build time, to prove the link works
    and to record what the bytes are -- and then throws the bytes away.

    A `tar:` path is relative to the root of the downloaded archive, which is
    also its path in the repository, so it can be named directly rather than
    making somebody fetch twenty megabytes of theme to see one screenshot.
    """
    kind, _, rest = where.partition(":")
    if kind == "url":
        url = GREETER_PICTURES.get(rest) or (ASTRONAUT_SHOTS + rest)
    else:
        repo, ref = GREETER_REPOS[REPO_OF[key]]
        url = "https://raw.githubusercontent.com/%s/%s/%s" % (repo, ref, rest)
    data = get(url, binary=True)
    for mime, head in (("image/png", b"\x89PNG"), ("image/jpeg", b"\xff\xd8\xff")):
        if data.startswith(head):
            break
    else:
        raise SystemExit("%s is not a picture -- the link is broken" % url)
    if len(data) > MAX_SHOT_BYTES:
        raise SystemExit("%s is %.1f MB; a screenshot stops at %d MB"
                         % (url, len(data) / 1048576.0,
                            MAX_SHOT_BYTES // (1 << 20)))
    return {"url": url, "type": mime, "bytes": len(data),
            "sha256": hashlib.sha256(data).hexdigest()}


def greeters():
    """The greeters map and the cards that point into it."""
    specs = {}
    trees = {}
    for key, repo_key, subpath, install_as, author, licence in GREETERS:
        digest, files = tree_digest_of(repo_key, subpath)
        trees[key] = files
        repo, ref = GREETER_REPOS[repo_key]
        url, data = greeter_archive(repo_key)
        meta = files.get("metadata.desktop", b"").decode("utf-8", "replace")
        if "QtVersion=6" not in meta.replace(" ", ""):
            raise SystemExit("%s does not say QtVersion=6, so it is a Qt5 "
                             "theme and would not come up" % key)
        specs[key] = {
            "name": repo.split("/")[1],
            "source": "https://github.com/%s/tree/%s" % (repo, ref),
            "author": author,
            "license": licence,
            "url": url,
            "sha256": hashlib.sha256(data).hexdigest(),
            "bytes": len(data),
            "subpath": "/".join(x for x in (archive_root(repo_key), subpath) if x),
            "tree": digest,
            "install_as": install_as,
            "needs": greeter_needs(files),
            "confs": greeter_confs(files),
        }

    out = []
    for (ident, key, conf, name, blurb, tags, picture) in GREETER_ITEMS:
        spec = specs[key]
        if conf and conf not in spec["confs"]:
            raise SystemExit("%s asks for %s, which %s does not have"
                             % (ident, conf, key))
        action = {"action": "greeter", "key": key}
        if conf:
            action["conf"] = conf
        out.append({
            "id": "login-" + ident,
            "section": "login",
            "name": name,
            "blurb": blurb,
            "family": "login",
            "author": spec["author"],
            "license": spec["license"],
            "source": spec["source"],
            "tags": ["login", "antes da sessão"] + tags,
            "needs_root": True,
            "download": spec["bytes"],
            "preview": {"kind": "login", "theme": key,
                        "shot": greeter_picture(ident, key, picture)},
            "actions": [action],
        })
    return specs, out


if __name__ == "__main__":
    build()
