"""
leaf-matrix.py — draw the Genesi mark as block characters, from the real SVG.

    python genesi-arch/devtools/leaf-matrix.py

Genesi Center's terminal plate shows the leaf as a dot matrix. Typing something
leaf-shaped by hand is how a brand mark drifts: it looks close, nobody compares
it to the logo again, and a year later they are two different marks. So it is
RASTERISED from art/genesi-leaf.svg, and there is only ever one drawing.

Re-run it after the logo changes; it rewrites the string in OverviewPage.qml in
place and asserts on the block it replaces, so a rewritten page fails loudly
rather than silently leaving the old mark.

A monospace cell is about half as wide as it is tall, so the sample grid is
twice as wide as it is tall -- sampling square would squash the leaf.
"""
import io
import os
import shutil

os.environ.setdefault("QT_QPA_PLATFORM", "offscreen")
from PySide6.QtGui import QGuiApplication, QImage, QPainter, QColor
from PySide6.QtSvg import QSvgRenderer
from PySide6.QtCore import Qt

REPO = "D:/Desenvolvimento/Genesi"
PKG = f"{REPO}/genesi-arch/packages/genesi-center"
# The leaf WITH the pulse line through it: that is the mark on the mockup, and
# the plymouth outline reads as a plain diamond once it is small.
SRC = f"{REPO}/genesi-arch/packages/genesi-ai-mode/monitor/icons/logo.svg"
DST = f"{PKG}/app/art/genesi-leaf.svg"

app = QGuiApplication([])
shutil.copyfile(SRC, DST)


def matrix(src, cols, rows):
    # A monospace cell is about half as wide as it is tall, so the sample grid
    # is twice as wide as it is tall or the mark comes out squashed.
    img = QImage(cols * 2, rows * 2, QImage.Format_ARGB32)
    img.fill(Qt.transparent)
    p = QPainter(img)
    QSvgRenderer(src).render(p)
    p.end()
    ramp = [" ", "\u2591", "\u2593"]
    out = []
    for y in range(rows):
        line = ""
        for x in range(cols):
            a = sum(QColor.fromRgba(img.pixel(x * 2 + dx, y * 2 + dy)).alpha()
                    for dx in (0, 1) for dy in (0, 1)) / 4.0
            line += ramp[0] if a < 40 else (ramp[1] if a < 150 else ramp[2])
        out.append(line.rstrip())
    while out and not out[0].strip():
        out.pop(0)
    while out and not out[-1].strip():
        out.pop()
    return out


rows = matrix(DST, 24, 11)
art = "\\n".join(rows)
print(f"matrix: {len(rows)} rows")
for r in rows:
    print("   " + r.replace("\u2593", "#").replace("\u2591", "."))

# ── OverviewPage: the terminal plate ─────────────────────────────────────────
p = f"{PKG}/app/pages/OverviewPage.qml"
s = io.open(p, encoding="utf-8").read()

OLD = '''                Text {
                    text: "░▒▓ ▒░  ▓▒░▒▓\\n ▒▓█ ☘ █▓▒ ░\\n░▒▓ ▒░  ▓▒░▒▓"
                    color: Tokens.accentDeep
                    font.family: Tokens.mono
                    font.pixelSize: 12
                    lineHeight: 1.15
                }'''
NEW = ('''                // The mark, rasterised from art/genesi-leaf.svg rather than
                // typed. Generated by devtools/leaf-matrix.py, so the terminal
                // plate and the logo can never drift apart.
                Text {
                    text: "%s"
                    color: Tokens.accentDim
                    font.family: Tokens.mono
                    font.pixelSize: 7
                    lineHeight: 1.0
                }''' % art)
assert s.count(OLD) == 1, "terminal art block not found"
s = s.replace(OLD, NEW, 1)

# The core plate's "ready" mark.
OLD_R = '''                    Text {
                        text: "☘"
                        color: Tokens.accent
                        font.pixelSize: 11
                    }'''
NEW_R = '''                    Image {
                        source: "../art/genesi-leaf.svg"
                        sourceSize: Qt.size(12, 12)
                        width: 12; height: 12
                        anchors.verticalCenter: parent.verticalCenter
                    }'''
assert s.count(OLD_R) == 1
s = s.replace(OLD_R, NEW_R, 1)
io.open(p, "w", encoding="utf-8", newline="\n").write(s)

# ── Main.qml: rail brand, footer plate, the unbuilt-page mark ────────────────
m = f"{PKG}/app/Main.qml"
s = io.open(m, encoding="utf-8").read()

pairs = [
    ('''                    Text {
                        text: "☘"
                        color: Tokens.accent
                        font.pixelSize: 26
                        anchors.verticalCenter: parent.verticalCenter
                    }''',
     '''                    Image {
                        source: "art/genesi-leaf.svg"
                        sourceSize: Qt.size(30, 30)
                        width: 30; height: 30
                        anchors.verticalCenter: parent.verticalCenter
                    }'''),
    ('''                        Text {
                            text: "☘"
                            color: Tokens.accent
                            font.pixelSize: 13
                            anchors.verticalCenter: parent.verticalCenter
                        }''',
     '''                        Image {
                            source: "art/genesi-leaf.svg"
                            sourceSize: Qt.size(14, 14)
                            width: 14; height: 14
                            anchors.verticalCenter: parent.verticalCenter
                        }'''),
    ('''                    Text {
                        anchors.horizontalCenter: parent.horizontalCenter
                        text: "☘"
                        color: Tokens.accentDeep
                        font.pixelSize: 44
                    }''',
     '''                    Image {
                        anchors.horizontalCenter: parent.horizontalCenter
                        source: "art/genesi-leaf.svg"
                        sourceSize: Qt.size(46, 46)
                        width: 46; height: 46
                        opacity: 0.35
                    }'''),
]
for old, new in pairs:
    assert s.count(old) == 1, old[:60]
    s = s.replace(old, new, 1)
io.open(m, "w", encoding="utf-8", newline="\n").write(s)

print("\nthe shamrock is gone; the mark is the real leaf everywhere")
